# Generated by Claude
"""A commit review window for the An-Cheon.github.io blog.

Lists everything git sees as changed, groups it into commits by this repo's
own convention (see CLAUDE.md), fills in the messages it can derive, leaves
the rest for the user to write, and pushes only after an explicit click.

Run it with `tools\\commit-gui.cmd`, or:

    python tools\\commit_gui.py

Lives under `tools/` on purpose: `_config.yml` lists `tools` in `exclude`, so
Jekyll never copies any of it into `_site/`. A `.py` left in the repository
root would be published at https://an-cheon.github.io/<name>.py.
"""

__version__ = "1.0.0"
