# Generated by Claude
"""Small Windows/Qt helpers, trimmed down from Code/MirrorSync/app_utils.py.

Only the three pieces this tool actually needs are kept: the dark native
title bar (a light caption over a dark window is the one thing that gives a
themed app away), a crash handler so an exception in a slot shows a dialog
instead of vanishing into a console nobody is watching, and the monospace
font the diff panel is measured in.
"""
from __future__ import annotations

import sys
import traceback

from PySide6.QtGui import QFont, QFontDatabase
from PySide6.QtWidgets import QMessageBox

from . import theme


def apply_dark_title_bar(widget):
    """Ask Windows DWM to draw the native title bar dark (attribute 20 on
    Win11/recent Win10, 19 on older builds). No-op elsewhere or on failure."""
    if sys.platform != "win32":
        return
    try:
        import ctypes
        hwnd = int(widget.winId())
        value = ctypes.c_int(1)
        for attribute in (20, 19):
            result = ctypes.windll.dwmapi.DwmSetWindowAttribute(
                hwnd, attribute, ctypes.byref(value), ctypes.sizeof(value))
            if result == 0:
                break
    except Exception:
        pass


def mono_font(point_size=10) -> QFont:
    """The first monospace family actually installed, not a hopeful string.

    Setting a font family Qt cannot find silently falls back to the UI font,
    and a proportional diff misaligns every hunk header.
    """
    available = set(QFontDatabase.families())
    for family in theme.MONO_FAMILIES:
        if family in available:
            font = QFont(family)
            break
    else:
        font = QFontDatabase.systemFont(QFontDatabase.SystemFont.FixedFont)
    font.setPointSize(point_size)
    font.setStyleHint(QFont.StyleHint.Monospace)
    return font


def install_crash_handler(app_name="Commit GUI"):
    """Show unhandled exceptions instead of letting Qt swallow them.

    Qt does not propagate a Python exception raised inside a slot; without
    this the window simply stops responding to a button with no clue why.
    """
    previous = sys.excepthook
    seen: set[str] = set()

    def hook(exc_type, exc_value, exc_tb):
        if issubclass(exc_type, KeyboardInterrupt):
            previous(exc_type, exc_value, exc_tb)
            return
        detail = "".join(traceback.format_exception(exc_type, exc_value, exc_tb))
        print(detail, file=sys.stderr)
        signature = f"{exc_type.__name__}:{exc_value}"
        if signature in seen:
            return                      # a repeating paint error must not
        seen.add(signature)             # stack a hundred dialogs
        try:
            box = QMessageBox()
            box.setIcon(QMessageBox.Icon.Critical)
            box.setWindowTitle(f"{app_name} — unexpected error")
            box.setText(f"{exc_type.__name__}: {exc_value}")
            box.setDetailedText(detail)
            box.exec()
        except Exception:
            pass

    sys.excepthook = hook
