# Generated by Claude
"""Every call into git goes through here.

Three things this repository forces and that a naive `subprocess.run("git ...")`
gets wrong:

1. **Non-ASCII paths.** `_posts/` holds names like `2019-10-1-优秀的绵羊.md`.
   Git escapes those to octal (`"\\344\\275\\240..."`) unless
   `core.quotepath=false`, so that flag is prepended to *every* invocation
   here rather than left to each caller to remember.

2. **Bytes in, bytes out.** Output is captured as bytes and decoded
   explicitly with `surrogateescape`, never left to the console code page.
   A path that survives the round trip is the one git will match again when
   we hand it back as a pathspec; `for_display()` makes a separate, lossy
   copy for the screen, because a lone surrogate reaching Qt is a crash.

3. **No console flash.** Without `CREATE_NO_WINDOW` every one of the dozens
   of git calls a refresh makes pops a black console window on Windows.

The environment is also pinned: `GIT_TERMINAL_PROMPT=0` so a push that needs
credentials fails in a second instead of blocking forever on a prompt nobody
can see, and `GIT_OPTIONAL_LOCKS=0` so read-only calls never take
`index.lock` out from under a git running in another window.
"""
from __future__ import annotations

import os
import shutil
import subprocess
import sys
import threading

CREATE_NO_WINDOW = getattr(subprocess, "CREATE_NO_WINDOW", 0)

DEFAULT_TIMEOUT = 60          # seconds; local git calls take milliseconds
PUSH_TIMEOUT = 300            # a push over a slow link, plus GCM's dialog

# Prepended to every invocation. `-c` options must come before the subcommand.
_GLOBAL_ARGS = ["-c", "core.quotepath=false", "-c", "color.ui=false"]


class GitMissing(RuntimeError):
    """git is not installed, or not on PATH."""


class GitFailed(RuntimeError):
    """A git call returned non-zero. Carries enough to show the user."""

    def __init__(self, argv, code, stderr):
        self.argv = list(argv)
        self.code = code
        self.stderr = stderr or ""
        detail = self.stderr.strip() or f"exit code {code}"
        super().__init__(f"git {' '.join(argv[:3])}: {detail}")


def git_executable():
    """Absolute path to git.exe, or raise GitMissing."""
    found = shutil.which("git")
    if not found:
        raise GitMissing(
            "git was not found. Make sure Git for Windows is installed and "
            "on PATH.")
    return found


def _env():
    """A pinned environment. See the module docstring for the why of each."""
    env = os.environ.copy()
    env["GIT_TERMINAL_PROMPT"] = "0"
    env["GIT_OPTIONAL_LOCKS"] = "0"
    env["GIT_PAGER"] = "cat"
    env["GIT_EDITOR"] = "true"      # nothing here may ever open an editor
    # A stale GIT_DIR/GIT_WORK_TREE inherited from a parent shell would point
    # git at a different repository than the one on screen.
    for leaked in ("GIT_DIR", "GIT_WORK_TREE", "GIT_INDEX_FILE",
                   "GIT_OBJECT_DIRECTORY"):
        env.pop(leaked, None)
    return env


def _flags():
    return CREATE_NO_WINDOW if sys.platform == "win32" else 0


# ── decoding ──────────────────────────────────────────────────────────────

def decode_path(raw: bytes) -> str:
    """Decode a path git printed, preserving bytes that are not valid UTF-8.

    `surrogateescape` means a path we cannot read is still a path we can hand
    back to git unchanged. Everything in this repository is real UTF-8, so
    the surrogate branch is insurance, not a code path that runs.
    """
    return raw.decode("utf-8", "surrogateescape")


def decode_text(raw: bytes) -> str:
    """Decode git's human-readable output for display. Lossy on purpose."""
    return raw.decode("utf-8", "replace")


def for_display(path: str) -> str:
    """A version of `path` that is safe to put in a Qt widget.

    Round-trips through bytes so any surrogate from `decode_path` becomes
    U+FFFD instead of raising deep inside Qt's text layout.
    """
    return path.encode("utf-8", "surrogateescape").decode("utf-8", "replace")


def literal(path: str) -> str:
    """Wrap a path as a pathspec that matches itself and nothing else.

    Without `:(literal)`, a filename containing `*`, `?` or a leading `:`
    would be read as a glob or as pathspec magic. No post is named that way
    today, but the cost of being right is four characters.
    """
    return ":(literal)" + path


# ── running ───────────────────────────────────────────────────────────────

class Result:
    __slots__ = ("argv", "code", "err", "out")

    def __init__(self, argv, code, out, err):
        self.argv = argv
        self.code = code
        self.out = out              # bytes
        self.err = err              # str

    @property
    def text(self) -> str:
        return decode_text(self.out)

    def check(self) -> Result:
        if self.code != 0:
            raise GitFailed(self.argv, self.code, self.err)
        return self


def run(repo, args, timeout=DEFAULT_TIMEOUT, check=True) -> Result:
    """Run one git command in `repo` and return its raw output.

    Raises GitFailed on a non-zero exit unless `check=False`; a timeout is
    reported the same way, so callers have one failure shape to handle.
    """
    argv = [git_executable(), *_GLOBAL_ARGS, *args]
    try:
        completed = subprocess.run(
            argv, cwd=str(repo), env=_env(), capture_output=True,
            timeout=timeout, creationflags=_flags())
    except subprocess.TimeoutExpired:
        raise GitFailed(args, -1,
                        f"Timed out after {timeout}s: git {' '.join(args[:3])}")
    except OSError as exc:
        raise GitFailed(args, -1, str(exc))
    result = Result(args, completed.returncode, completed.stdout,
                    decode_text(completed.stderr))
    return result.check() if check else result


def run_lines(repo, args, **kwargs):
    """Run and split stdout on NUL, dropping the trailing empty field."""
    raw = run(repo, args, **kwargs).out
    parts = raw.split(b"\0")
    if parts and parts[-1] == b"":
        parts.pop()
    return parts


def stream(repo, args, on_line, timeout=PUSH_TIMEOUT, cancelled=None):
    """Run git and report each output line as it arrives.

    Used for push, which is the only call here that can take long enough that
    the user needs to see it move. stderr is merged into stdout because git
    writes progress to stderr and the porcelain report to stdout, and the log
    panel wants them interleaved in the order they happened.

    `cancelled` is an optional `threading.Event`; when it is set the child is
    killed. Returns the exit code (-1 if it was killed).
    """
    argv = [git_executable(), *_GLOBAL_ARGS, *args]
    try:
        proc = subprocess.Popen(
            argv, cwd=str(repo), env=_env(), stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT, stdin=subprocess.DEVNULL,
            creationflags=_flags())
    except OSError as exc:
        raise GitFailed(args, -1, str(exc))

    timer = threading.Timer(timeout, proc.kill)
    timer.daemon = True
    timer.start()
    try:
        assert proc.stdout is not None
        for raw in proc.stdout:
            if cancelled is not None and cancelled.is_set():
                proc.kill()
                break
            # git uses \r to redraw progress counters; each fragment is a
            # line as far as the log panel is concerned.
            for piece in decode_text(raw).replace("\r", "\n").split("\n"):
                if piece.strip():
                    on_line(piece.rstrip())
        proc.wait(timeout=10)
    except Exception:
        proc.kill()
        raise
    finally:
        timer.cancel()
        if proc.stdout is not None:
            proc.stdout.close()
    return proc.returncode if proc.returncode is not None else -1
