# Generated by Claude
"""Entry point: build the application, find the repository, show the window.

No single-instance guard, unlike MirrorSync. Two copies of this window cannot
corrupt anything -- each one re-reads the working tree immediately before it
writes, and git's own `index.lock` serialises the writes -- so the guard would
only be tidiness, and tidiness is not worth a socket.
"""
from __future__ import annotations

import os
import sys

from PySide6.QtGui import QColor, QPalette
from PySide6.QtWidgets import QApplication, QMessageBox

from . import app_utils, gitcmd, model, theme
from .window import MainWindow


def build_palette() -> QPalette:
    """ValueCheck's dark palette, so the tools look like one toolkit."""
    palette = QPalette()
    palette.setColor(QPalette.ColorRole.Window, QColor(60, 63, 65))
    palette.setColor(QPalette.ColorRole.WindowText, QColor(169, 183, 198))
    palette.setColor(QPalette.ColorRole.Base, QColor(43, 43, 43))
    palette.setColor(QPalette.ColorRole.AlternateBase, QColor(60, 63, 65))
    palette.setColor(QPalette.ColorRole.ToolTipBase, QColor(60, 63, 65))
    palette.setColor(QPalette.ColorRole.ToolTipText, QColor(169, 183, 198))
    palette.setColor(QPalette.ColorRole.Text, QColor(169, 183, 198))
    palette.setColor(QPalette.ColorRole.Button, QColor(60, 63, 65))
    palette.setColor(QPalette.ColorRole.ButtonText, QColor(169, 183, 198))
    palette.setColor(QPalette.ColorRole.Highlight, QColor(54, 88, 128))
    palette.setColor(QPalette.ColorRole.HighlightedText, QColor(255, 255, 255))
    palette.setColor(QPalette.ColorRole.PlaceholderText, QColor(120, 130, 140))
    return palette


def _default_start() -> str:
    """The blog root: this file is `<repo>/tools/commitgui/main.py`."""
    return os.path.dirname(os.path.dirname(os.path.dirname(
        os.path.abspath(__file__))))


def main(argv=None) -> int:
    argv = list(sys.argv if argv is None else argv)
    app = QApplication(argv)
    app.setApplicationName("Commit GUI")
    app.setStyle("Fusion")          # the palette below only takes under Fusion
    app.setPalette(build_palette())
    app.setStyleSheet(theme.build_stylesheet() + theme.MESSAGEBOX_QSS)
    app.setWindowIcon(theme.app_icon())
    app_utils.install_crash_handler()

    start = argv[1] if len(argv) > 1 else _default_start()
    if not os.path.isdir(start):
        QMessageBox.critical(None, "Path not found",
                            f"No such directory:\n{start}")
        return 2
    try:
        repo = model.find_repo_root(start)
    except gitcmd.GitMissing as exc:
        QMessageBox.critical(None, "git not found", str(exc))
        return 2
    except gitcmd.GitFailed as exc:
        QMessageBox.critical(
            None, "Not a git repository",
            f"{start}\n\nis not inside a git repository.\n\n{exc}")
        return 2

    window = MainWindow(repo)
    window.open_maximized()
    return app.exec()


if __name__ == "__main__":
    raise SystemExit(main())
