# Generated by Claude
"""Reading the working tree: what changed, by how much, and where HEAD is.

The one design decision worth stating up front: **nothing here filters by
file type.** Classification (in `rules.py`) decides what a change is *called*
in a commit message; it never decides whether a change is *shown*. A `.py`
script, a `.png` cover, a `.rb` plugin and a post are all rows in the same
list, and a change this module cannot name still appears -- in the group that
asks the user to name it. That is the whole point of the tool: no silent
omissions.

Two smaller decisions:

* `--no-renames` on both the status and the numstat call. Git's `-z` rename
  records carry *two* NUL-separated fields instead of one, which is the
  classic off-by-one in porcelain parsers. Turning renames off makes every
  record uniform -- a rename becomes a delete plus an add, which is also
  exactly how `_plugins/posts-lastmod-hook.rb` reads the same history.
* Ignored files are fetched separately and lazily. `-uall` is required to
  list untracked files individually, but combined with `--ignored` it would
  walk every file under `_site/` and `vendor/`.
"""
from __future__ import annotations

import os
from dataclasses import dataclass, field

from . import gitcmd

# XY pairs that mean "this path has a merge conflict". Committing one of
# these without resolving it records the conflict markers into history.
UNMERGED = {"DD", "AU", "UD", "UA", "DU", "AA", "UU"}

IMAGE_SUFFIXES = {".png", ".jpg", ".jpeg", ".gif", ".webp", ".bmp", ".svg",
                  ".ico", ".avif"}

# Sentinels for `Change.added`, which is a line count everywhere else.
BINARY = -1
TOO_LARGE = -2

# Reading a whole file to render it as a diff has to stop somewhere.
MAX_PREVIEW_BYTES = 512 * 1024
MAX_PREVIEW_LINES = 3000
BINARY_SNIFF_BYTES = 8000


@dataclass
class Change:
    """One path git reports as different from HEAD."""

    path: str                     # exact, as git printed it
    index_status: str             # X of the porcelain XY pair
    work_status: str              # Y
    status: str                   # effective: A / M / D / R / U
    added: int = 0                # lines, -1 when binary
    deleted: int = 0
    untracked: bool = False
    unmerged: bool = False
    submodule: bool = False

    @property
    def display(self) -> str:
        return gitcmd.for_display(self.path)

    @property
    def name(self) -> str:
        return self.display.rsplit("/", 1)[-1]

    @property
    def suffix(self) -> str:
        _, ext = os.path.splitext(self.path)
        return ext.lower()

    @property
    def is_image(self) -> bool:
        return self.suffix in IMAGE_SUFFIXES

    @property
    def binary(self) -> bool:
        return self.added == BINARY

    @property
    def too_large(self) -> bool:
        """Skipped for size, not because it is binary. The two used to share
        one sentinel, and a 600 KB Markdown post read as `binary`."""
        return self.added == TOO_LARGE

    def churn(self) -> str:
        """`+12 -3`, or a word when there are no line counts to show."""
        if self.status == "D":
            return "deleted"
        if self.binary:
            return "binary"
        if self.too_large:
            return "large file"
        bits = []
        if self.added:
            bits.append(f"+{self.added}")
        if self.deleted:
            bits.append(f"-{self.deleted}")
        return "  ".join(bits) if bits else "no line changes"


@dataclass
class RepoState:
    """Everything the header bar and the guards need to know."""

    root: str
    branch: str                    # "" when detached
    detached: bool = False
    upstream: str = ""
    ahead: int = 0
    behind: int = 0
    head_subject: str = ""
    unborn: bool = False           # on a branch, but it has no commits yet
    in_progress: str = ""          # "merge" / "rebase" / "cherry-pick" / ""
    changes: list[Change] = field(default_factory=list)

    @property
    def blocked(self) -> str:
        """Why committing must not be allowed right now, or ""."""
        if self.in_progress:
            return (f"A {self.in_progress} is in progress. Finish or abort it "
                    f"on the command line before committing here.")
        if any(c.unmerged for c in self.changes):
            return ("There are unresolved merge conflicts. Resolve them "
                    "before committing.")
        if self.detached:
            return ("HEAD is detached — a commit made here would not belong "
                    "to any branch.")
        return ""


# ── repository discovery ──────────────────────────────────────────────────

def find_repo_root(start) -> str:
    """The top level of the working tree containing `start`."""
    out = gitcmd.run(start, ["rev-parse", "--show-toplevel"]).text.strip()
    if not out:
        raise gitcmd.GitFailed(["rev-parse"], 1, "Not a git repository.")
    return os.path.normpath(out)


def _git_dir(repo) -> str:
    """Absolute .git directory. Not always `repo/.git` (worktrees, submodules)."""
    out = gitcmd.run(repo, ["rev-parse", "--absolute-git-dir"]).text.strip()
    return out or os.path.join(repo, ".git")


def _in_progress(repo) -> str:
    """Name the multi-step operation the repository is in the middle of."""
    git_dir = _git_dir(repo)

    def here(*parts):
        return os.path.exists(os.path.join(git_dir, *parts))

    if here("MERGE_HEAD"):
        return "merge"
    if here("rebase-merge") or here("rebase-apply"):
        return "rebase"
    if here("CHERRY_PICK_HEAD"):
        return "cherry-pick"
    if here("REVERT_HEAD"):
        return "revert"
    if here("BISECT_LOG"):
        return "bisect"
    return ""


# ── status ────────────────────────────────────────────────────────────────

def _effective_status(x: str, y: str) -> str:
    """Collapse git's two-letter code into the one letter a commit records.

    The question being answered is "if this path is staged and committed
    right now, what does the commit say happened to it?" -- so the worktree
    side wins for deletions (a file staged as modified but since deleted on
    disk is a deletion), and an untracked file is an addition.
    """
    if x == "?" or y == "?":
        return "A"
    if x == "!" or y == "!":
        return "!"
    if x + y in UNMERGED:
        return "U"
    if y == "D" or x == "D":
        return "D"
    if x == "A":
        return "A"
    if x == "R" or y == "R":
        return "R"
    if x == "C":
        return "A"
    return "M"


def _parse_porcelain(raw: bytes):
    """Yield (X, Y, path) from `status --porcelain=v1 -z --no-renames`.

    Each record is `XY<space><path>`; `--no-renames` guarantees there is no
    second field, which is what keeps this loop a loop and not a state
    machine.
    """
    for record in raw.split(b"\0"):
        if len(record) < 4:
            continue
        x = chr(record[0])
        y = chr(record[1])
        yield x, y, gitcmd.decode_path(record[3:])


def _numstat(repo) -> dict[str, tuple[int, int]]:
    """Per-path (added, deleted) between HEAD and the working tree.

    Binary files come back as `-` for both counts and are recorded as
    (BINARY, BINARY) so `Change.binary` can tell "no lines" from "zero lines".
    """
    counts: dict[str, tuple[int, int]] = {}
    try:
        raw = gitcmd.run(repo, ["diff", "HEAD", "--numstat", "-z",
                                "--no-renames"]).out
    except gitcmd.GitFailed:
        return counts            # no HEAD yet (empty repo) -- not fatal
    for record in raw.split(b"\0"):
        if not record:
            continue
        parts = record.split(b"\t", 2)
        if len(parts) != 3:
            continue
        added, deleted, path = parts
        try:
            pair = (int(added), int(deleted))
        except ValueError:
            pair = (BINARY, BINARY)      # "-" means binary
        counts[gitcmd.decode_path(path)] = pair
    return counts


def _untracked_counts(repo, changes):
    """Line counts for untracked files, which `git diff HEAD` cannot see."""
    for change in changes:
        if not change.untracked or change.status == "D":
            continue
        full = os.path.join(repo, change.path.replace("/", os.sep))
        try:
            size = os.path.getsize(full)
            if size > MAX_PREVIEW_BYTES:
                change.added = TOO_LARGE
                continue
            with open(full, "rb") as handle:
                data = handle.read()
        except OSError:
            continue
        if b"\0" in data[:BINARY_SNIFF_BYTES]:
            change.added = BINARY
        else:
            change.added = data.count(b"\n") + (
                1 if data and not data.endswith(b"\n") else 0)


def _submodule_paths(repo) -> set[str]:
    """Paths registered as submodules, so they are never grouped as content."""
    try:
        raw = gitcmd.run(repo, ["config", "-z", "--file", ".gitmodules",
                                "--get-regexp", r"path$"], check=False)
    except gitcmd.GitFailed:
        return set()
    paths = set()
    for record in raw.out.split(b"\0"):
        if b"\n" in record:
            _key, value = record.split(b"\n", 1)
            paths.add(gitcmd.decode_path(value))
    return paths


def _branch_info(repo, state: RepoState) -> None:
    # `symbolic-ref` is the authority on "am I on a branch", and it is the
    # only one that answers before the first commit: on an unborn branch
    # `rev-parse --abbrev-ref HEAD` fails outright (measured on git 2.53),
    # which an earlier version read as a detached HEAD and then refused to
    # commit to a repository that was merely empty.
    branch = gitcmd.run(repo, ["symbolic-ref", "--short", "-q", "HEAD"],
                        check=False).text.strip()
    if branch:
        state.branch = branch
        state.unborn = gitcmd.run(repo, ["rev-parse", "--verify", "-q", "HEAD"],
                                  check=False).code != 0
    else:
        state.detached = True
        state.branch = gitcmd.run(repo, ["rev-parse", "--short", "HEAD"],
                                  check=False).text.strip()

    upstream = gitcmd.run(repo, ["rev-parse", "--abbrev-ref",
                                 "--symbolic-full-name", "@{u}"],
                          check=False)
    if upstream.code == 0:
        state.upstream = upstream.text.strip()
        counts = gitcmd.run(repo, ["rev-list", "--left-right", "--count",
                                   "@{u}...HEAD"], check=False)
        if counts.code == 0:
            parts = counts.text.split()
            if len(parts) == 2:
                state.behind, state.ahead = int(parts[0]), int(parts[1])

    state.head_subject = gitcmd.run(
        repo, ["log", "-1", "--pretty=%s"], check=False).text.strip()


def scan(repo) -> RepoState:
    """One full read of the repository. Safe to call from a worker thread."""
    state = RepoState(root=str(repo), branch="")
    _branch_info(repo, state)
    state.in_progress = _in_progress(repo)

    raw = gitcmd.run(repo, ["status", "--porcelain=v1", "-z", "-uall",
                            "--no-renames", "--ignored=no"]).out
    submodules = _submodule_paths(repo)
    counts = _numstat(repo)

    changes = []
    for x, y, path in _parse_porcelain(raw):
        status = _effective_status(x, y)
        added, deleted = counts.get(path, (0, 0))
        changes.append(Change(
            path=path, index_status=x, work_status=y, status=status,
            added=added, deleted=deleted,
            untracked=(x == "?"),
            unmerged=(x + y in UNMERGED),
            submodule=(path in submodules),
        ))
    _untracked_counts(repo, changes)
    changes.sort(key=lambda c: c.path.lower())
    state.changes = changes
    return state


def scan_ignored(repo, limit=400):
    """Paths .gitignore is hiding, collapsed at the directory level.

    Deliberately a separate call from `scan`: this one runs without `-uall`
    so `_site/` comes back as one entry instead of ten thousand. Shown only
    when the user expands the panel -- the point is to let them confirm that
    what is missing is missing on purpose.
    """
    raw = gitcmd.run(repo, ["status", "--porcelain=v1", "-z", "-unormal",
                            "--no-renames", "--ignored=traditional"],
                     check=False).out
    found = [path for x, _y, path in _parse_porcelain(raw) if x == "!"]
    found.sort(key=str.lower)
    return found[:limit], len(found)
