# Generated by Claude
"""Turning a list of changed files into commit groups with messages.

The rules are read off this repository's own history rather than invented.
Sampling the last 200 commits: `fix` 24, `post` 15, `config` 15, `update` 10,
matching the convention in CLAUDE.md. Two patterns in that history drive the
design here:

* `post: Stumbling on Happiness, Where the Money Is` -- several new posts of
  the same kind share one commit, titles joined with ", " in post-date order.
* `1017aa3 post: ...` and `1ccb001 update: ...` carry the *same* timestamp:
  one session's work was split into one commit per kind, not merged into a
  catch-all. So grouping is by kind, and each group commits separately.

What is deliberately *not* automated: `fix:`, `feat:` and `config:` bodies,
and any deletion. Those describe intent, and a rule that guessed at intent
would produce exactly the unreadable history the convention exists to avoid.
Those groups arrive with a prefix and an empty description, and the UI will
not let them be committed until the user types one.

Titles come from the front matter's `title:`, never from the filename --
filenames carry a `2026-9-5-` prefix and are inconsistently punctuated.
"""
from __future__ import annotations

import os
import re
from dataclasses import dataclass, field

from . import gitcmd
from .model import Change

# _posts/<optional subdir>/YYYY-M-D-<name>.md  (subdirs: Investing/, Others/)
POST_RE = re.compile(
    r"^_posts/(?:[^/]+/)*(\d{4})-(\d{1,2})-(\d{1,2})-(.+)\.(?:md|markdown)$",
    re.IGNORECASE)

TITLE_RE = re.compile(r"^title:[ \t]*(.+?)[ \t]*$", re.MULTILINE)

# Files whose change is a site-configuration change, per the `config:` commits
# in the history (`_config.yml`, the deploy workflow, the theme's data files).
CONFIG_FILES = {
    "_config.yml", "gemfile", "gemfile.lock", ".gitignore", ".gitmodules",
    ".editorconfig", ".nojekyll", ".gitattributes",
}
CONFIG_PREFIXES = (".github/", "_data/")

IMAGE_DIR = "images/"

# Order groups are shown and committed in: content first, then configuration,
# then the two that need the user, so the ones needing attention sit together
# at the bottom of the list.
KIND_ORDER = {"post": 0, "update": 1, "config": 2, "other": 3, "remove": 4}

KIND_PREFIX = {
    "post": "post: ",
    "update": "update: ",
    "config": "config: ",
    "other": "fix: ",
    "remove": "remove: ",
}

KIND_LABEL = {
    "post": "New post",
    "update": "Edited post",
    "config": "Site config",
    "other": "Other changes",
    "remove": "Deletions",
}

KIND_HINT = {
    "config": 'Say what configuration changed, e.g. "set site url ..."',
    "other": 'Describe the change, e.g. "speed up build by ..."',
    "remove": "Say why this is being deleted — deletions are never filled in",
}


@dataclass
class Group:
    kind: str
    changes: list[Change] = field(default_factory=list)
    message: str = ""
    auto: bool = False              # message was generated, not typed
    user_edited: bool = False

    @property
    def key(self) -> str:
        """Stable across a refresh as long as the file set is unchanged.

        Used to carry a half-typed description through a rescan. If the set
        of files moves, the key moves with it and the text is dropped -- a
        description written for other files is worse than an empty box.
        """
        paths = "\x00".join(sorted(c.path for c in self.changes))
        return f"{self.kind}\x01{paths}"

    @property
    def label(self) -> str:
        return KIND_LABEL.get(self.kind, self.kind)

    @property
    def hint(self) -> str:
        return KIND_HINT.get(self.kind, "")

    @property
    def needs_text(self) -> bool:
        return not self.auto

    def ready(self) -> bool:
        return is_ready(self.message)


def is_ready(message: str) -> bool:
    """True when `message` says something beyond its prefix.

    `"fix: "` strips to `"fix:"` and is rejected by the trailing-colon test,
    which is why the prefix is stored with its trailing space.
    """
    text = message.strip()
    return bool(text) and not text.endswith(":")


# ── titles ────────────────────────────────────────────────────────────────

def _front_matter_title(text: str) -> str:
    """The `title:` of a Jekyll post, or "" when there is no front matter."""
    text = text.removeprefix("﻿")
    if not text.lstrip().startswith("---"):
        return ""
    body = text.lstrip()[3:]
    end = body.find("\n---")
    block = body[:end] if end != -1 else body[:4000]
    found = TITLE_RE.search(block)
    if not found:
        return ""
    title = found.group(1).strip()
    if len(title) >= 2 and title[0] == title[-1] and title[0] in "\"'":
        title = title[1:-1].strip()
    return title


def _read_worktree(repo, path, limit=200_000) -> str:
    full = os.path.join(repo, path.replace("/", os.sep))
    try:
        with open(full, "rb") as handle:
            return handle.read(limit).decode("utf-8", "replace")
    except OSError:
        return ""


def _read_head(repo, path, limit=200_000) -> str:
    """The HEAD version of a path -- the only place to look for the title of
    a post that has just been deleted from disk."""
    result = gitcmd.run(repo, ["show", f"HEAD:{path}"], check=False)
    if result.code != 0:
        return ""
    return result.out[:limit].decode("utf-8", "replace")


def _title_from_filename(path: str) -> str:
    found = POST_RE.match(path)
    return found.group(4) if found else os.path.basename(path)


def post_title(repo, change: Change) -> str:
    """Best available title for a post, falling back to its filename."""
    text = (_read_head(repo, change.path) if change.status == "D"
            else _read_worktree(repo, change.path))
    return _front_matter_title(text) or _title_from_filename(change.path)


def post_date(path: str):
    found = POST_RE.match(path)
    if not found:
        return (0, 0, 0)
    return tuple(int(found.group(i)) for i in (1, 2, 3))


# ── image attachment ──────────────────────────────────────────────────────

def _normalise(name: str) -> str:
    """`Where_the_Money_Is_3.png` -> `where the money is`.

    Trailing `_3` is dropped because a post's images are numbered; the rest
    is the book title with underscores for spaces, which is how the covers in
    `images/` have been named all along.
    """
    stem = os.path.splitext(name)[0]
    stem = re.sub(r"[_\- ]\d+$", "", stem)
    stem = re.sub(r"[_\-]+", " ", stem)
    return re.sub(r"\s+", " ", stem).strip().casefold()


def _attach_images(images, posts, contents):
    """Map each image change onto a post, or leave it unattached.

    Two signals, strongest first. A post that *references* the file is proof;
    name similarity is a guess that happens to be right for every cover in
    this repository but would be wrong for a shared asset.
    """
    attached: dict[str, Change] = {}      # image path -> owning post path
    unattached = []
    by_norm = {}
    for post in posts:
        for key in (_normalise(os.path.basename(post.path)),
                    _normalise(contents.get(post.path, ("", ""))[1])):
            if key:                   # `images/_1.png` normalises to "", and
                by_norm.setdefault(key, post)   # so does a missing title

    for image in images:
        base = os.path.basename(image.path)
        owner = None
        for post in posts:
            text = contents.get(post.path, ("", ""))[0]
            if base and base in text:
                owner = post
                break
        if owner is None:
            owner = by_norm.get(_normalise(base)) if _normalise(base) else None
        if owner is not None:
            attached[image.path] = owner
        else:
            unattached.append(image)
    return attached, unattached


# ── grouping ──────────────────────────────────────────────────────────────

def _is_config(path: str) -> bool:
    lowered = path.lower()
    if lowered in CONFIG_FILES:
        return True
    return any(lowered.startswith(prefix) for prefix in CONFIG_PREFIXES)


def auto_message(kind: str, titles) -> str:
    """The generated subject for a group, from its posts' titles."""
    prefix = KIND_PREFIX.get(kind, "")
    return prefix + ", ".join(titles) if titles else prefix


def build_groups(repo, changes) -> list[Group]:
    """Partition `changes` into commit groups.

    Every change lands in exactly one group. There is no branch that drops a
    file: anything the rules cannot name falls through to `other`, which
    carries an empty description and blocks its own commit until the user
    writes one.
    """
    posts_add, posts_mod, removed, images, config, other = [], [], [], [], [], []

    for change in changes:
        path = change.path
        if change.submodule:
            other.append(change)
        elif POST_RE.match(path) and change.status in ("A", "M", "D"):
            if change.status == "A":
                posts_add.append(change)
            elif change.status == "M":
                posts_mod.append(change)
            else:
                removed.append(change)
        elif change.status == "D":
            removed.append(change)
        elif path.lower().startswith(IMAGE_DIR) and change.is_image:
            images.append(change)
        elif _is_config(path):
            config.append(change)
        else:
            other.append(change)

    # Titles and bodies, read once: image attachment needs the body, the
    # message needs the title.
    contents: dict[str, tuple[str, str]] = {}
    for change in posts_add + posts_mod + removed:
        if not POST_RE.match(change.path):
            continue
        text = (_read_head(repo, change.path) if change.status == "D"
                else _read_worktree(repo, change.path))
        title = _front_matter_title(text) or _title_from_filename(change.path)
        contents[change.path] = (text, title)

    attached, orphan_images = _attach_images(
        images, posts_add + posts_mod, contents)
    other.extend(orphan_images)

    groups: list[Group] = []

    def content_group(kind, posts):
        if not posts:
            return
        members = list(posts)
        owned = {p.path for p in posts}
        members.extend(img for img in images
                       if attached.get(img.path) is not None
                       and attached[img.path].path in owned)
        members.sort(key=lambda c: c.path.lower())
        groups.append(Group(kind=kind, changes=members, auto=True))

    content_group("post", posts_add)
    content_group("update", posts_mod)

    for kind, members in (("config", config), ("other", other),
                          ("remove", removed)):
        if members:
            groups.append(Group(
                kind=kind, auto=False, message=KIND_PREFIX[kind],
                changes=sorted(members, key=lambda c: c.path.lower())))

    groups.sort(key=lambda g: KIND_ORDER.get(g.kind, 99))
    for group in groups:
        if group.auto:
            group.message = message_for(group, contents,
                                        [c.path for c in group.changes])
    return groups


def message_for(group: Group, contents, selected_paths) -> str:
    """Regenerate an auto message for whichever files are still ticked.

    Unticking one of two new posts has to change `post: A, B` into `post: A`,
    or the commit would name a file it does not contain. Called again on
    every checkbox change, and skipped once the user has typed over it.
    """
    if not group.auto:
        return group.message
    chosen = set(selected_paths)
    titles = []
    for change in group.changes:
        if change.path not in chosen:
            continue
        entry = contents.get(change.path)
        if entry is None:
            continue
        titles.append((post_date(change.path), entry[1]))
    titles.sort(key=lambda item: (item[0], item[1]))
    seen, ordered = set(), []
    for _date, title in titles:
        if title not in seen:
            seen.add(title)
            ordered.append(title)
    return auto_message(group.kind, ordered)


def titles_map(repo, changes) -> dict[str, tuple[str, str]]:
    """`{path: (body, title)}` for every post among `changes`."""
    out = {}
    for change in changes:
        if not POST_RE.match(change.path):
            continue
        text = (_read_head(repo, change.path) if change.status == "D"
                else _read_worktree(repo, change.path))
        out[change.path] = (text, _front_matter_title(text)
                            or _title_from_filename(change.path))
    return out
