# Generated by Claude
"""IntelliJ-style dark theme for the commit GUI.

Copied from Code/MirrorSync/theme.py, which in turn copied it from
Code/ValueCheck/pyside6_split/ratiolens/theme.py, so this tool looks like the
rest of the toolkit. Kept as a private copy rather than imported: this file
lives in a *different repository* from ValueCheck and cannot import it, and
the blog must stay clonable on its own.

The stock-specific helpers of the original (ratio bands, FCFY colors, the
star icon) are dropped -- there is no ratio here to color. The color tokens
and the stylesheet are verbatim so the windows match pixel for pixel; the
only addition is STATUS_COLORS, which reuses ValueCheck's own band colors for
git's A/M/D letters.
"""
from __future__ import annotations

import math

from PySide6.QtCore import QPointF, QRectF, Qt
from PySide6.QtGui import QColor, QIcon, QPainter, QPen, QPixmap, QPolygonF

BG_WINDOW = QColor(60, 63, 65)      # #3C3F41
BG_BASE = QColor(43, 43, 43)        # #2B2B2B
BG_PANEL = QColor(49, 51, 53)       # #313335
FG_TEXT = QColor(169, 183, 198)     # #A9B7C6
FG_DIM = QColor(120, 130, 140)
ACCENT = QColor(75, 110, 175)       # #4B6EAF
GRID = QColor(75, 78, 80)
GOLD = QColor(240, 195, 80)

# ValueCheck's five band colors, reused for git's status letters. Green for
# what is new, amber for what changed, red for what is going away -- the same
# reading direction the stock tables use.
GREEN = QColor(106, 135, 89)
GREEN_LIGHT = QColor(140, 185, 120)
AMBER = QColor(188, 143, 65)
ORANGE = QColor(204, 120, 50)
RED = QColor(188, 63, 60)
BLUE = QColor(122, 167, 220)

STATUS_COLORS = {
    "A": GREEN_LIGHT,   # added / untracked
    "M": AMBER,         # modified
    "D": RED,           # deleted
    "R": BLUE,          # renamed
    "U": ORANGE,        # unmerged - needs the user before anything else
    "!": FG_DIM,        # ignored
}

STATUS_LABELS = {
    "A": "added",
    "M": "modified",
    "D": "deleted",
    "R": "renamed",
    "U": "conflict",
    "!": "ignored",
}

# Diff colors. Deliberately dimmer than the status colors: a diff is a wall
# of them, and the band greens read as neon over a whole screen.
DIFF_ADD = QColor(122, 168, 106)
DIFF_DEL = QColor(190, 110, 108)
DIFF_HUNK = QColor(110, 145, 195)
DIFF_META = QColor(120, 130, 140)

MONO_FAMILIES = ("Cascadia Mono", "Consolas", "Microsoft YaHei Mono",
                 "Courier New", "monospace")


# ---- procedurally drawn icons (anti-aliased, crisp at any DPI) ------------

_ICON_SIZES = (16, 20, 24, 32, 48, 64)
_ICON_BLUE = QColor(122, 167, 220)
_ICON_BLUE_DARK = QColor(94, 143, 204)


def _icon_pixmaps(draw):
    """Build a QIcon by drawing the glyph fresh at each standard size."""
    icon = QIcon()
    for size in _ICON_SIZES:
        pixmap = QPixmap(size, size)
        pixmap.fill(Qt.GlobalColor.transparent)
        painter = QPainter(pixmap)
        painter.setRenderHint(QPainter.RenderHint.Antialiasing)
        draw(painter, size / 16.0)
        painter.end()
        icon.addPixmap(pixmap)
    return icon


def refresh_icon():
    """Circular arrow with a round-capped stroke and smooth arrowhead."""
    def draw(painter, u):
        pen = QPen(_ICON_BLUE, 1.9 * u)
        pen.setCapStyle(Qt.PenCapStyle.RoundCap)
        painter.setPen(pen)
        painter.setBrush(Qt.BrushStyle.NoBrush)
        center, radius = 8 * u, 5.0 * u
        rect = QRectF(center - radius, center - radius, 2 * radius, 2 * radius)
        painter.drawArc(rect, 30 * 16, -245 * 16)  # clockwise, gap at top
        px = center - 0.819 * radius
        py = center - 0.574 * radius
        dx, dy = 0.574, -0.819          # clockwise tangent at 145 deg
        nx, ny = -dy, dx
        painter.setPen(Qt.PenStyle.NoPen)
        painter.setBrush(_ICON_BLUE)
        painter.drawPolygon(QPolygonF([
            QPointF(px + dx * 3.6 * u, py + dy * 3.6 * u),
            QPointF(px + nx * 2.3 * u, py + ny * 2.3 * u),
            QPointF(px - nx * 2.3 * u, py - ny * 2.3 * u),
        ]))
    return _icon_pixmaps(draw)


def app_icon():
    """A commit node on a branch line: a filled circle on a vertical stroke."""
    def draw(painter, u):
        pen = QPen(_ICON_BLUE_DARK, 1.8 * u)
        pen.setCapStyle(Qt.PenCapStyle.RoundCap)
        painter.setPen(pen)
        painter.drawLine(QPointF(8 * u, 1.6 * u), QPointF(8 * u, 14.4 * u))
        painter.setPen(Qt.PenStyle.NoPen)
        painter.setBrush(GOLD)
        radius = 3.4 * u
        painter.drawEllipse(QRectF(8 * u - radius, 8 * u - radius,
                                   2 * radius, 2 * radius))
    return _icon_pixmaps(draw)


def _unused_star():  # pragma: no cover - kept so the copy can be diffed
    """The original theme's star, unused here. See the module docstring."""
    def draw(painter, u):
        painter.setPen(Qt.PenStyle.NoPen)
        painter.setBrush(GOLD)
        cx = cy = 8 * u
        outer, inner = 6.4 * u, 2.7 * u
        points = []
        for i in range(10):
            radius = outer if i % 2 == 0 else inner
            angle = math.radians(90 + i * 36)
            points.append(QPointF(cx + radius * math.cos(angle),
                                  cy - radius * math.sin(angle)))
        painter.drawPolygon(QPolygonF(points))
    return _icon_pixmaps(draw)


STYLESHEET = """
QWidget { background-color: #3C3F41; color: #A9B7C6; font-size: 12px;
          font-family: "Microsoft YaHei UI", "Malgun Gothic", "Segoe UI",
                       sans-serif; }
QMainWindow, QDialog { background-color: #3C3F41; }
QLineEdit, QDoubleSpinBox, QComboBox {
    background-color: #313335; color: #A9B7C6;
    border: 1px solid #2B2B2B; border-radius: 3px; padding: 3px 6px;
}
QLineEdit:focus, QDoubleSpinBox:focus { border: 1px solid #4B6EAF; }
QLineEdit:disabled { color: #6E7A85; background-color: #35383A; }
QPushButton {
    background-color: #4C5052; color: #A9B7C6;
    border: 1px solid #2B2B2B; border-radius: 3px; padding: 4px 12px;
}
QPushButton:hover { background-color: #4B6EAF; color: #FFFFFF; }
QPushButton:pressed { background-color: #3D5A8F; }
QPushButton:disabled { background-color: #3F4244; color: #6E7A85; }
QPushButton#primary {
    background-color: #365880; color: #C8D4E0; font-weight: bold;
}
QPushButton#primary:hover { background-color: #4A6A8C; color: #FFFFFF; }
QPushButton#primary:pressed { background-color: #2D4A66; }
QPushButton#primary:disabled { background-color: #3F4244; color: #6E7A85;
                               font-weight: normal; }
QListWidget, QTableWidget, QTreeWidget, QPlainTextEdit, QTextEdit {
    background-color: #2B2B2B; color: #A9B7C6;
    border: 1px solid #2B2B2B; alternate-background-color: #313335;
}
QTreeWidget::item, QListWidget::item { padding: 3px 4px; }
QListWidget::item:selected, QTableWidget::item:selected,
QTreeWidget::item:selected {
    background-color: rgba(75, 110, 175, 0.55); color: #FFFFFF;
}
QTreeWidget::branch { background: transparent; }
QHeaderView::section {
    background-color: #3C3F41; color: #A9B7C6;
    border: 1px solid #2B2B2B; padding: 4px;
}
QTableCornerButton::section { background-color: #3C3F41; border: 1px solid #2B2B2B; }
QGroupBox {
    border: 1px solid #2B2B2B; border-radius: 3px;
    margin-top: 8px; padding-top: 8px;
}
QGroupBox::title { subcontrol-origin: margin; left: 8px; padding: 0 4px;
                   color: #A9B7C6; }
QRadioButton, QCheckBox, QLabel { background: transparent; }
QSplitter::handle { background-color: #2B2B2B; }
QScrollArea { border: none; }
QScrollArea > QWidget > QWidget { background-color: #3C3F41; }
QMenuBar { background-color: #3C3F41; color: #A9B7C6;
           border-bottom: 1px solid #2B2B2B; }
QMenuBar::item { background: transparent; padding: 4px 10px; }
QMenuBar::item:selected { background-color: #4B6EAF; color: #FFFFFF; }
QMenu { background-color: #3C3F41; color: #A9B7C6; border: 1px solid #2B2B2B; }
QMenu::item { padding: 5px 28px 5px 20px; }
QMenu::item:selected { background-color: #4B6EAF; color: #FFFFFF; }
QMenu::separator { height: 1px; background: #2B2B2B; margin: 4px 8px; }
QStatusBar { background-color: #313335; color: #A9B7C6; }
QStatusBar::item { border: none; }
QProgressBar {
    background-color: #2B2B2B; border: 1px solid #2B2B2B; border-radius: 3px;
    text-align: center; color: #A9B7C6;
}
QProgressBar::chunk { background-color: #4B6EAF; border-radius: 2px; }
QScrollBar:vertical { background: #3C3F41; width: 12px; }
QScrollBar::handle:vertical { background: #5A5A5A; min-height: 20px; border-radius: 4px; }
QScrollBar::handle:vertical:hover { background: #6A6A6A; }
QScrollBar:horizontal { background: #3C3F41; height: 12px; }
QScrollBar::handle:horizontal { background: #5A5A5A; min-width: 20px; border-radius: 4px; }
QScrollBar::handle:horizontal:hover { background: #6A6A6A; }
QScrollBar::add-line, QScrollBar::sub-line { width: 0; height: 0; }
QScrollBar::add-page, QScrollBar::sub-page { background: none; }
QToolTip { background-color: #313335; color: #A9B7C6; border: 1px solid #4B6EAF; }
"""

MESSAGEBOX_QSS = """
    QMessageBox { background-color: #2B2B2B; }
    QMessageBox QLabel { color: #A9B7C6; }
    QMessageBox QPushButton {
        background-color: #365880; color: #A9B7C6;
        border: 1px solid #3C3F41; border-radius: 4px;
        padding: 6px 16px; min-width: 70px;
    }
    QMessageBox QPushButton:hover { background-color: #4A6A8C; }
"""


def build_stylesheet(font_px=12):
    """The theme stylesheet with an adjustable base font size."""
    return STYLESHEET.replace("font-size: 12px", f"font-size: {int(font_px)}px")
