# Generated by Claude
"""The window.

Header, then the work area, then a log, then the buttons. The work area is a
stack of two pages, because a repository with nothing to commit is a
different screen and not an empty version of the same one: a tree with a
header row and no rows under it, next to a panel saying "select a file on the
left", reads as a program that failed to load rather than as good news.

The rules the UI enforces, all of them there to make a wrong commit hard:

* A group whose message is still just its prefix cannot be committed. The
  buttons stay *enabled* and say why when clicked -- an earlier version
  disabled them, and a dead button with the reason only in the status bar
  reads as a broken program rather than as a question waiting for an answer.
  Clicking now jumps to the box that needs typing and outlines it in amber.
* Unticking a file rewrites its group's generated message, so the subject
  can never name a post the commit does not contain -- unless the user has
  typed over it, in which case their text is never touched.
* Push is confirmed separately from commit, because a push to master starts
  the Pages deploy.
* Merge in progress, conflicted files or a detached HEAD show a banner and
  block committing entirely. That one *does* disable the buttons: it is not
  a question the user can answer from this window.

Every background result carries the scan generation it belongs to. A refresh
calls `tree.clear()`, which deletes the item objects; a worker that finishes
afterwards would otherwise write into freed widgets.

The interface is English, matching `_config.yml`'s `lang: en`, the `config:
switch UI to English` commit in this repo's history, and the sibling tools.
"""
from __future__ import annotations

import os
from collections import Counter

from PySide6.QtCore import Qt, QTimer, Signal
from PySide6.QtGui import (
    QColor,
    QFont,
    QGuiApplication,
    QPixmap,
    QSyntaxHighlighter,
    QTextCharFormat,
)
from PySide6.QtWidgets import (
    QFrame,
    QHBoxLayout,
    QHeaderView,
    QLabel,
    QLineEdit,
    QMainWindow,
    QMessageBox,
    QPlainTextEdit,
    QProgressBar,
    QPushButton,
    QScrollArea,
    QSizePolicy,
    QSplitter,
    QStackedWidget,
    QTreeWidget,
    QTreeWidgetItem,
    QVBoxLayout,
    QWidget,
)

from . import app_utils, gitcmd, rules, theme
from .workers import CommitWorker, DiffWorker, IgnoredWorker, ScanWorker

ROLE = Qt.ItemDataRole.UserRole
CIRCLED = "①②③④⑤⑥⑦⑧⑨⑩⑪⑫⑬⑭⑮⑯⑰⑱⑲⑳"

CARD_QSS = ("QFrame#card {{ background-color: #313335; border: 1px solid {};"
            " border-radius: 4px; }}")

QUIET_BUTTON_QSS = """
QPushButton#quiet {
    background: transparent; border: none; color: #78828C;
    padding: 2px 8px; text-align: left;
}
QPushButton#quiet:hover { color: #A9B7C6; background: #35383A; }
QPushButton#quiet:checked { color: #A9B7C6; }
"""


def files_label(count: int) -> str:
    return "1 file" if count == 1 else f"{count} files"


def badge_for(index: int) -> str:
    return CIRCLED[index] if index < len(CIRCLED) else str(index + 1)


class DiffHighlighter(QSyntaxHighlighter):
    """Colour a unified diff. Order matters: `+++` and `---` are headers, not
    an added and a removed line, so they are tested before the bare signs."""

    def __init__(self, document):
        super().__init__(document)
        self.add = self._fmt(theme.DIFF_ADD)
        self.remove = self._fmt(theme.DIFF_DEL)
        self.hunk = self._fmt(theme.DIFF_HUNK, bold=True)
        self.meta = self._fmt(theme.DIFF_META)

    @staticmethod
    def _fmt(color: QColor, bold=False) -> QTextCharFormat:
        fmt = QTextCharFormat()
        fmt.setForeground(color)
        if bold:
            fmt.setFontWeight(QFont.Weight.Bold)
        return fmt

    def highlightBlock(self, text):
        if not text:
            return
        if text.startswith(("+++", "---")):
            style = self.meta
        elif text.startswith("@@"):
            style = self.hunk
        elif text.startswith("+"):
            style = self.add
        elif text.startswith("-"):
            style = self.remove
        elif text.startswith(("diff ", "index ", "new file", "deleted file",
                              "similarity", "rename ", "old mode", "new mode",
                              "Binary files", "\\ No newline", "New file",
                              "...")):
            style = self.meta
        else:
            return
        self.setFormat(0, len(text), style)


class ImageView(QLabel):
    """A QLabel that keeps its pixmap fitted to whatever size it is given."""

    def __init__(self):
        super().__init__()
        self.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.setMinimumSize(80, 80)
        self._source: QPixmap | None = None

    def show_image(self, path: str):
        pixmap = QPixmap(path)
        self._source = None if pixmap.isNull() else pixmap
        if self._source is None:
            self.setText("Cannot display this image.")
        self._rescale()

    def _rescale(self):
        if self._source is None:
            return
        area = self.size()
        if area.width() < 8 or area.height() < 8:
            return
        self.setPixmap(self._source.scaled(
            area, Qt.AspectRatioMode.KeepAspectRatio,
            Qt.TransformationMode.SmoothTransformation))

    def resizeEvent(self, event):
        super().resizeEvent(event)
        self._rescale()


class GroupCard(QFrame):
    """One editable commit message, with the state of its group beside it."""

    edited = Signal(str)          # group key
    focused = Signal(str)         # group key

    def __init__(self, index: int, group: rules.Group):
        super().__init__()
        self.group = group
        self.setObjectName("card")
        self._alerted = False
        self.setStyleSheet(CARD_QSS.format("#2B2B2B"))
        outer = QHBoxLayout(self)
        outer.setContentsMargins(10, 8, 10, 8)
        outer.setSpacing(10)

        badge = QLabel(badge_for(index))
        badge.setStyleSheet("color: #F0C350; font-size: 17px;")
        badge.setFixedWidth(22)
        badge.setAlignment(Qt.AlignmentFlag.AlignTop
                           | Qt.AlignmentFlag.AlignHCenter)
        outer.addWidget(badge)

        column = QVBoxLayout()
        column.setSpacing(4)
        outer.addLayout(column, 1)

        top = QHBoxLayout()
        top.setSpacing(8)
        kind = QLabel(group.label)
        kind.setStyleSheet(
            f"color: {kind_colour(group.kind).name()}; font-weight: bold;")
        top.addWidget(kind)
        self.count = QLabel(files_label(len(group.changes)))
        self.count.setStyleSheet(f"color: {theme.FG_DIM.name()};")
        top.addWidget(self.count)
        top.addStretch(1)
        self.state = QLabel()
        top.addWidget(self.state)
        column.addLayout(top)

        self.editor = QLineEdit(group.message)
        self.editor.setPlaceholderText(group.hint or "Commit message")
        self.editor.textEdited.connect(self._on_typed)
        self.editor.installEventFilter(self)
        column.addWidget(self.editor)

        if group.hint:
            hint = QLabel(group.hint)
            hint.setStyleSheet(f"color: {theme.FG_DIM.name()}; font-size: 11px;")
            hint.setWordWrap(True)
            column.addWidget(hint)

        self.refresh()

    def eventFilter(self, watched, event):
        if watched is self.editor and event.type() == event.Type.FocusIn:
            self.focused.emit(self.group.key)
        return super().eventFilter(watched, event)

    def _on_typed(self, text):
        self.group.user_edited = True
        self.group.message = text
        self.set_alert(False)
        self.refresh()
        self.edited.emit(self.group.key)

    def set_message(self, text: str):
        """Push a regenerated message in without marking it user-edited."""
        if self.editor.text() != text:
            blocked = self.editor.blockSignals(True)
            self.editor.setText(text)
            self.editor.blockSignals(blocked)
        self.group.message = text
        self.refresh()

    def set_selected_count(self, count: int):
        total = len(self.group.changes)
        self.count.setText(f"{count} of {total} files" if count != total
                           else files_label(total))
        self.editor.setEnabled(count > 0)
        self.refresh(count)

    def set_alert(self, on: bool):
        """Outline the card in amber -- used when a click had to be refused."""
        if on == self._alerted:
            return
        self._alerted = on
        self.setStyleSheet(CARD_QSS.format(
            theme.AMBER.name() if on else "#2B2B2B"))

    def demand_input(self):
        """Put the caret exactly where the missing description has to go."""
        self.set_alert(True)
        self.editor.setFocus(Qt.FocusReason.OtherFocusReason)
        self.editor.setCursorPosition(len(self.editor.text()))

    def refresh(self, count=None):
        if count == 0:
            self.state.setText("○ none selected")
            self.state.setStyleSheet(f"color: {theme.FG_DIM.name()};")
        elif self.group.ready():
            self.state.setText("✔ ready")
            self.state.setStyleSheet(f"color: {theme.GREEN_LIGHT.name()};")
        else:
            self.state.setText("⚠ needs a description")
            self.state.setStyleSheet(f"color: {theme.AMBER.name()};")


def kind_colour(kind: str) -> QColor:
    return {"post": theme.GREEN_LIGHT, "update": theme.AMBER,
            "config": theme.BLUE, "remove": theme.RED,
            "other": theme.FG_DIM}.get(kind, theme.FG_TEXT)


class EmptyState(QWidget):
    """The screen for a repository with nothing to commit.

    Deliberately not an empty tree: a clean working tree is the normal state
    of this repository between posts, and it should look like an answer
    rather than like a view that failed to populate.
    """

    def __init__(self, parent=None):
        super().__init__(parent)
        outer = QVBoxLayout(self)
        outer.setContentsMargins(40, 40, 40, 40)
        outer.addStretch(1)

        mark = QLabel("✔")
        mark.setAlignment(Qt.AlignmentFlag.AlignCenter)
        mark.setStyleSheet(
            f"color: {theme.GREEN_LIGHT.name()}; font-size: 40px;")
        outer.addWidget(mark)

        self.title = QLabel("Working tree is clean")
        self.title.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.title.setStyleSheet(
            f"color: {theme.FG_TEXT.name()}; font-size: 17px;")
        outer.addWidget(self.title)

        self.detail = QLabel()
        self.detail.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.detail.setWordWrap(True)
        self.detail.setStyleSheet(f"color: {theme.FG_DIM.name()};")
        outer.addSpacing(6)
        outer.addWidget(self.detail)

        row = QHBoxLayout()
        row.setSpacing(8)
        row.addStretch(1)
        self.refresh_button = QPushButton("Refresh")
        row.addWidget(self.refresh_button)
        self.ignored_button = QPushButton("Show ignored files")
        row.addWidget(self.ignored_button)
        self.push_button = QPushButton("Push")
        self.push_button.setObjectName("primary")
        row.addWidget(self.push_button)
        row.addStretch(1)
        outer.addSpacing(18)
        outer.addLayout(row)

        outer.addStretch(2)

    def update_for(self, state):
        if state.unborn:
            self.title.setText("No commits yet")
            self.detail.setText(
                f"{state.branch} has no history yet. Write a post, then "
                f"come back and it will be the first commit.")
            self.push_button.setVisible(False)
            return
        self.title.setText("Working tree is clean")
        bits = []
        if state.ahead:
            bits.append(f"{state.ahead} local commit(s) not pushed")
        if state.behind:
            bits.append(f"{state.behind} commit(s) waiting on the remote")
        if not state.upstream:
            bits.append(f"{state.branch} has no upstream branch")
        if bits:
            self.detail.setText(" · ".join(bits) + ".")
        else:
            self.detail.setText(
                f"Nothing to commit on {state.branch}"
                + (f", in sync with {state.upstream}." if state.upstream
                   else "."))
        self.push_button.setVisible(bool(state.ahead) and not state.detached)
        self.push_button.setText(f"Push {state.ahead} commit(s)")


class MainWindow(QMainWindow):

    def __init__(self, repo: str):
        super().__init__()
        self.repo = repo
        self.state = None
        self.groups: list[rules.Group] = []
        self.contents: dict = {}
        self.cards: dict[str, GroupCard] = {}
        self.preserved: dict[str, str] = {}
        self._updating = False
        self._diff_generation = 0
        self._scan_generation = 0
        self._workers: list = []
        self._commit_worker: CommitWorker | None = None
        self._ignored_loaded = False

        self.setWindowTitle(f"Commit · {os.path.basename(repo)}")
        self.setWindowIcon(theme.app_icon())
        self.resize(1320, 880)
        self._build_ui()
        app_utils.apply_dark_title_bar(self)
        QTimer.singleShot(0, self.refresh)

    def open_maximized(self):
        """Show the window filling the primary screen.

        Windows 11 does not round the corners of a maximized window -- the
        frame is placed past the screen edges, so the rounding DWM draws
        falls outside the visible area. Filling the screen was chosen over
        keeping the rounded corners; the two cannot both be had.

        The window is moved onto the primary screen before it is maximized,
        because a window maximizes onto whichever screen it currently sits
        on and Qt's default placement is not guaranteed to be that one.
        """
        screen = QGuiApplication.primaryScreen()
        if screen is not None:
            area = screen.availableGeometry()
            self.move(area.x() + 40, area.y() + 40)
        self.showMaximized()

    # ── construction ─────────────────────────────────────────────────

    def _build_ui(self):
        central = QWidget()
        self.setCentralWidget(central)
        root = QVBoxLayout(central)
        root.setContentsMargins(10, 8, 10, 8)
        root.setSpacing(8)

        root.addLayout(self._build_header())

        self.banner = QLabel()
        self.banner.setWordWrap(True)
        self.banner.setStyleSheet(
            f"background-color: #4A2B2B; color: {theme.RED.lighter(140).name()};"
            " border: 1px solid #5A3333; border-radius: 3px; padding: 6px 10px;")
        self.banner.hide()
        root.addWidget(self.banner)

        self.pages = QStackedWidget()
        self.pages.addWidget(self._build_workspace())
        self.empty_page = EmptyState()
        self.empty_page.refresh_button.clicked.connect(self.refresh)
        self.empty_page.ignored_button.clicked.connect(self._reveal_ignored)
        self.empty_page.push_button.clicked.connect(self._on_push_only)
        self.pages.addWidget(self.empty_page)
        root.addWidget(self.pages, 1)

        self.log = QPlainTextEdit()
        self.log.setReadOnly(True)
        self.log.setFont(app_utils.mono_font(9))
        self.log.setFixedHeight(112)
        self.log.hide()             # only appears once there is output
        root.addWidget(self.log)

        root.addLayout(self._build_footer())

    def _build_header(self):
        row = QHBoxLayout()
        row.setSpacing(10)

        self.repo_label = QLabel(os.path.basename(self.repo))
        self.repo_label.setStyleSheet(
            f"color: {theme.FG_TEXT.name()}; font-size: 14px; font-weight: bold;")
        self.repo_label.setToolTip(self.repo)
        row.addWidget(self.repo_label)

        self.branch_label = QLabel("…")
        self.branch_label.setStyleSheet(f"color: {theme.GOLD.name()};")
        row.addWidget(self.branch_label)

        self.sync_label = QLabel("")
        self.sync_label.setStyleSheet(f"color: {theme.FG_DIM.name()};")
        row.addWidget(self.sync_label)

        row.addStretch(1)

        self.check_all = QPushButton("Select all")
        self.check_all.clicked.connect(lambda: self._set_all_checked(True))
        row.addWidget(self.check_all)

        self.check_none = QPushButton("Select none")
        self.check_none.clicked.connect(lambda: self._set_all_checked(False))
        row.addWidget(self.check_none)

        self.refresh_button = QPushButton(" Refresh")
        self.refresh_button.setIcon(theme.refresh_icon())
        self.refresh_button.clicked.connect(self.refresh)
        row.addWidget(self.refresh_button)
        return row

    def _build_workspace(self):
        self.work_split = QSplitter(Qt.Orientation.Horizontal)
        self.work_split.addWidget(self._build_tree())
        self.work_split.addWidget(self._build_right())
        self.work_split.setStretchFactor(0, 45)
        self.work_split.setStretchFactor(1, 55)
        self.work_split.setSizes([620, 760])
        return self.work_split

    def _build_tree(self):
        self.tree = QTreeWidget()
        self.tree.setColumnCount(3)
        self.tree.setHeaderLabels(["Change", "Status", "Lines"])
        self.tree.setRootIsDecorated(True)
        self.tree.setUniformRowHeights(True)
        header = self.tree.header()
        header.setStretchLastSection(False)
        header.setSectionResizeMode(0, QHeaderView.ResizeMode.Stretch)
        header.setSectionResizeMode(1, QHeaderView.ResizeMode.Fixed)
        header.setSectionResizeMode(2, QHeaderView.ResizeMode.Fixed)
        self.tree.setColumnWidth(1, 82)
        self.tree.setColumnWidth(2, 108)
        self.tree.itemChanged.connect(self._on_item_changed)
        self.tree.currentItemChanged.connect(self._on_item_selected)
        self.tree.itemExpanded.connect(self._on_item_expanded)
        return self.tree

    def _build_right(self):
        self.right_split = QSplitter(Qt.Orientation.Vertical)

        self.cards_area = QScrollArea()
        self.cards_area.setWidgetResizable(True)
        self.cards_host = QWidget()
        self.cards_layout = QVBoxLayout(self.cards_host)
        self.cards_layout.setContentsMargins(2, 2, 2, 2)
        self.cards_layout.setSpacing(6)
        self.cards_layout.addStretch(1)
        self.cards_area.setWidget(self.cards_host)
        self.cards_area.setMinimumHeight(84)
        self.right_split.addWidget(self.cards_area)

        self.preview = QStackedWidget()

        self.diff_view = QPlainTextEdit()
        self.diff_view.setReadOnly(True)
        self.diff_view.setFont(app_utils.mono_font(10))
        self.diff_view.setLineWrapMode(QPlainTextEdit.LineWrapMode.NoWrap)
        self.highlighter = DiffHighlighter(self.diff_view.document())
        self.preview.addWidget(self.diff_view)

        self.image_view = ImageView()
        self.image_view.setStyleSheet("background-color: #2B2B2B;")
        self.preview.addWidget(self.image_view)

        self.note_view = QLabel()
        self.note_view.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.note_view.setWordWrap(True)
        self.note_view.setStyleSheet(
            f"background-color: #2B2B2B; color: {theme.FG_DIM.name()};")
        self.preview.addWidget(self.note_view)

        self._show_note("Select a file on the left to see what changed.")
        self.right_split.addWidget(self.preview)

        self.right_split.setStretchFactor(0, 0)
        self.right_split.setStretchFactor(1, 1)
        self.right_split.setSizes([230, 620])
        return self.right_split

    def _build_footer(self):
        row = QHBoxLayout()
        row.setSpacing(10)

        self.log_toggle = QPushButton("▸ Log")
        self.log_toggle.setObjectName("quiet")
        self.log_toggle.setStyleSheet(QUIET_BUTTON_QSS)
        self.log_toggle.setCheckable(True)
        self.log_toggle.setFixedWidth(64)
        self.log_toggle.toggled.connect(self._set_log_visible)
        row.addWidget(self.log_toggle)

        self.status_label = QLabel("Reading…")
        self.status_label.setSizePolicy(QSizePolicy.Policy.Expanding,
                                        QSizePolicy.Policy.Preferred)
        row.addWidget(self.status_label, 1)

        self.progress = QProgressBar()
        self.progress.setFixedWidth(180)
        self.progress.hide()
        row.addWidget(self.progress)

        self.push_only_button = QPushButton("Push only")
        self.push_only_button.clicked.connect(self._on_push_only)
        row.addWidget(self.push_only_button)

        self.commit_button = QPushButton("Commit")
        self.commit_button.clicked.connect(lambda: self._start_commit(False))
        row.addWidget(self.commit_button)

        # "&&" because a single & is Qt's mnemonic marker and would render as
        # an underlined "p" instead of an ampersand.
        self.commit_push_button = QPushButton("Commit && push")
        self.commit_push_button.setObjectName("primary")
        self.commit_push_button.clicked.connect(lambda: self._start_commit(True))
        row.addWidget(self.commit_push_button)
        return row

    # ── scanning ─────────────────────────────────────────────────────

    def refresh(self):
        if self._commit_worker is not None:
            return
        self._remember_typed()
        self._scan_generation += 1
        self._set_busy(True, "Reading the working tree…")
        worker = ScanWorker(self.repo, self._scan_generation, self)
        worker.scanned.connect(self._on_scanned)
        worker.failed.connect(self._on_scan_failed)
        self._track(worker)
        worker.start()

    def _remember_typed(self):
        for key, card in self.cards.items():
            if card.group.user_edited and card.group.message.strip():
                self.preserved[key] = card.group.message

    def _track(self, worker):
        self._workers.append(worker)
        worker.finished.connect(lambda: self._workers.remove(worker)
                                if worker in self._workers else None)

    def _on_scan_failed(self, generation, message):
        if generation != self._scan_generation:
            return
        self._set_busy(False)
        self.status_label.setText("Read failed")
        self._append_log(message)
        QMessageBox.critical(self, "Could not read the repository", message)

    def _on_scanned(self, generation, state, groups, contents):
        if generation != self._scan_generation:
            return                      # a newer refresh already won
        self.state = state
        self.groups = groups
        self.contents = contents
        self._ignored_loaded = False

        for group in self.groups:
            saved = self.preserved.get(group.key)
            if saved:
                group.message = saved
                group.user_edited = True

        self._fill_header()
        self._fill_tree()
        self._fill_cards()
        self._sync_messages()
        self.pages.setCurrentWidget(
            self.empty_page if not self.groups else self.work_split)
        self.empty_page.update_for(state)
        self._set_busy(False)

    def _fill_header(self):
        state = self.state
        marker = "detached @ " if state.detached else ""
        self.branch_label.setText(f"{marker}{state.branch}")
        bits = []
        if state.unborn:
            bits.append("· no commits yet")
        elif state.upstream:
            if state.ahead:
                bits.append(f"↑{state.ahead}")
            if state.behind:
                bits.append(f"↓{state.behind}")
            bits.append(f"· {state.upstream}")
        else:
            bits.append("· no upstream")
        self.sync_label.setText("  ".join(bits))

        blocked = state.blocked
        self.banner.setVisible(bool(blocked))
        if blocked:
            self.banner.setText(blocked)

    def _fill_tree(self):
        self._updating = True
        self.tree.clear()
        for index, group in enumerate(self.groups):
            parent = QTreeWidgetItem(self.tree)
            parent.setData(0, ROLE, ("group", group.key))
            parent.setText(0, f"{badge_for(index)} {group.label}"
                              f"  ·  {files_label(len(group.changes))}")
            parent.setForeground(0, kind_colour(group.kind))
            font = parent.font(0)
            font.setBold(True)
            parent.setFont(0, font)
            parent.setFlags(parent.flags() | Qt.ItemFlag.ItemIsUserCheckable)

            for change in group.changes:
                child = QTreeWidgetItem(parent)
                child.setData(0, ROLE, ("file", change))
                child.setText(0, change.display)
                child.setToolTip(0, change.display)
                child.setText(1, theme.STATUS_LABELS.get(change.status,
                                                         change.status))
                child.setForeground(1, theme.STATUS_COLORS.get(
                    change.status, theme.FG_TEXT))
                child.setText(2, change.churn())
                child.setForeground(2, theme.FG_DIM)
                flags = child.flags() | Qt.ItemFlag.ItemIsUserCheckable
                if change.unmerged:
                    flags &= ~Qt.ItemFlag.ItemIsEnabled
                child.setFlags(flags)
                child.setCheckState(
                    0, Qt.CheckState.Unchecked if change.unmerged
                    else Qt.CheckState.Checked)
            # After the children, not before: a group whose files are all
            # conflicted has nothing ticked, and a ticked parent over
            # untickable children was a lie about what would be committed.
            self._sync_parent_state(parent)
            parent.setExpanded(True)

        self.ignored_item = QTreeWidgetItem(self.tree)
        self.ignored_item.setData(0, ROLE, ("ignored", None))
        self.ignored_item.setText(0, "Ignored by .gitignore (expand to view)")
        self.ignored_item.setForeground(0, theme.FG_DIM)
        self.ignored_item.setChildIndicatorPolicy(
            QTreeWidgetItem.ChildIndicatorPolicy.ShowIndicator)
        self._updating = False

        if self.groups:
            first = self.tree.topLevelItem(0)
            if first.childCount():
                self.tree.setCurrentItem(first.child(0))

    def _fill_cards(self):
        for card in self.cards.values():
            card.setParent(None)
            card.deleteLater()
        self.cards.clear()
        while self.cards_layout.count() > 1:
            item = self.cards_layout.takeAt(0)
            widget = item.widget()
            if widget is not None:
                widget.deleteLater()

        for index, group in enumerate(self.groups):
            card = GroupCard(index, group)
            card.edited.connect(lambda _key: self._update_actions())
            card.focused.connect(self._select_group)
            self.cards_layout.insertWidget(self.cards_layout.count() - 1, card)
            self.cards[group.key] = card
        QTimer.singleShot(0, self._fit_cards_pane)

    def _fit_cards_pane(self):
        """Give the message cards exactly the height they need.

        A fixed split left a third of the window as empty panel when there
        was one group, and scrolled when there were six.
        """
        if not self.cards:
            return
        total = self.right_split.height()
        if total < 200:
            return
        wanted = self.cards_host.sizeHint().height() + 6
        top = max(84, min(wanted, int(total * 0.55)))
        self.right_split.setSizes([top, total - top])

    # ── tree interaction ─────────────────────────────────────────────

    def _iter_group_items(self):
        for index in range(self.tree.topLevelItemCount()):
            item = self.tree.topLevelItem(index)
            data = item.data(0, ROLE)
            if data and data[0] == "group":
                yield item, data[1]

    def _group_item(self, key):
        for item, group_key in self._iter_group_items():
            if group_key == key:
                return item
        return None

    def _selected_paths(self, item) -> list[str]:
        paths = []
        for row in range(item.childCount()):
            child = item.child(row)
            if child.checkState(0) == Qt.CheckState.Checked:
                _kind, change = child.data(0, ROLE)
                paths.append(change.path)
        return paths

    def _on_item_changed(self, item, column):
        if self._updating or column != 0:
            return
        data = item.data(0, ROLE)
        if not data:
            return
        kind, _payload = data
        self._updating = True
        try:
            if kind == "group":
                target = item.checkState(0)
                if target != Qt.CheckState.PartiallyChecked:
                    for row in range(item.childCount()):
                        child = item.child(row)
                        if child.flags() & Qt.ItemFlag.ItemIsEnabled:
                            child.setCheckState(0, target)
            elif kind == "file":
                parent = item.parent()
                if parent is not None:
                    self._sync_parent_state(parent)
        finally:
            self._updating = False
        self._sync_messages()
        self._update_actions()

    @staticmethod
    def _sync_parent_state(parent):
        total = parent.childCount()
        checked = sum(1 for row in range(total)
                      if parent.child(row).checkState(0) == Qt.CheckState.Checked)
        if checked == 0:
            parent.setCheckState(0, Qt.CheckState.Unchecked)
        elif checked == total:
            parent.setCheckState(0, Qt.CheckState.Checked)
        else:
            parent.setCheckState(0, Qt.CheckState.PartiallyChecked)

    def _set_all_checked(self, checked: bool):
        state = Qt.CheckState.Checked if checked else Qt.CheckState.Unchecked
        self._updating = True
        try:
            for item, _key in self._iter_group_items():
                for row in range(item.childCount()):
                    child = item.child(row)
                    if child.flags() & Qt.ItemFlag.ItemIsEnabled:
                        child.setCheckState(0, state)
                self._sync_parent_state(item)
        finally:
            self._updating = False
        self._sync_messages()
        self._update_actions()

    def _sync_messages(self):
        """Regenerate every auto message the user has not taken over."""
        for item, key in self._iter_group_items():
            card = self.cards.get(key)
            if card is None:
                continue
            paths = self._selected_paths(item)
            group = card.group
            if group.auto and not group.user_edited:
                card.set_message(rules.message_for(group, self.contents, paths))
            card.set_selected_count(len(paths))

    def _select_group(self, key):
        item = self._group_item(key)
        if item is not None:
            self.tree.setCurrentItem(item)

    def _on_item_selected(self, current, _previous):
        if current is None:
            return
        data = current.data(0, ROLE)
        if not data:
            return
        kind, payload = data
        if kind == "file":
            self._load_diff(payload)
        elif kind == "group":
            card = self.cards.get(payload)
            if card is not None:
                self.cards_area.ensureWidgetVisible(card)
                self._show_note(self._group_note(card.group,
                                                 self._selected_paths(current)))
        elif kind == "ignored":
            self._show_note(
                "These paths match a rule in .gitignore. They are listed so "
                "you can confirm that what is missing is missing on purpose; "
                "they are never staged, committed or pushed.")

    def _group_note(self, group, paths) -> str:
        chosen = set(paths)
        counts = Counter(theme.STATUS_LABELS.get(c.status, c.status)
                         for c in group.changes if c.path in chosen)
        breakdown = " · ".join(f"{n} {name}" for name, n in sorted(counts.items()))
        message = group.message.strip()
        subject = message if rules.is_ready(message) else "(no description yet)"
        return (f"{group.label}\n\n"
                f"{len(chosen)} of {files_label(len(group.changes))} selected"
                + (f"\n{breakdown}" if breakdown else "")
                + f"\n\nWill be committed as:\n{subject}")

    def _on_item_expanded(self, item):
        data = item.data(0, ROLE)
        if not data or data[0] != "ignored" or self._ignored_loaded:
            return
        self._ignored_loaded = True
        placeholder = QTreeWidgetItem(item)
        placeholder.setText(0, "Reading…")
        placeholder.setForeground(0, theme.FG_DIM)
        worker = IgnoredWorker(self.repo, self._scan_generation, self)
        worker.listed.connect(self._on_ignored)
        worker.failed.connect(
            lambda gen, msg: self._append_log(msg)
            if gen == self._scan_generation else None)
        self._track(worker)
        worker.start()

    def _reveal_ignored(self):
        """From the empty screen: show the tree just to look at the ignores."""
        self.pages.setCurrentWidget(self.work_split)
        item = getattr(self, "ignored_item", None)
        if item is not None:
            item.setExpanded(True)
            self.tree.setCurrentItem(item)

    def _on_ignored(self, generation, paths, total):
        # Without this the result of a scan the user has already refreshed
        # past would be written into tree items that `tree.clear()` deleted,
        # which raises "Internal C++ object already deleted".
        if generation != self._scan_generation:
            return
        item = getattr(self, "ignored_item", None)
        if item is None:
            return
        self._updating = True
        try:
            item.takeChildren()
            for path in paths:
                child = QTreeWidgetItem(item)
                child.setText(0, gitcmd.for_display(path))
                child.setText(1, "ignored")
                child.setForeground(0, theme.FG_DIM)
                child.setForeground(1, theme.FG_DIM)
            item.setText(
                0, f"Ignored by .gitignore — {total} items, never committed")
            if total > len(paths):
                more = QTreeWidgetItem(item)
                more.setText(0, f"… {total - len(paths)} more not listed")
                more.setForeground(0, theme.FG_DIM)
        finally:
            self._updating = False

    # ── diff preview ─────────────────────────────────────────────────

    def _show_note(self, text: str):
        self.note_view.setText(text)
        self.preview.setCurrentWidget(self.note_view)

    def _load_diff(self, change):
        self._diff_generation += 1
        generation = self._diff_generation
        self._show_note("Reading…")
        worker = DiffWorker(self.repo, change, generation, self)
        worker.ready.connect(self._on_diff_ready)
        worker.failed.connect(self._on_diff_failed)
        self._track(worker)
        worker.start()

    def _on_diff_ready(self, generation, _path, kind, payload):
        if generation != self._diff_generation:
            return                      # a newer selection already won
        if kind == "text":
            self.diff_view.setPlainText(payload)
            self.preview.setCurrentWidget(self.diff_view)
        elif kind == "image":
            self.image_view.show_image(payload)
            self.preview.setCurrentWidget(self.image_view)
        else:
            self._show_note(payload)

    def _on_diff_failed(self, generation, message):
        if generation != self._diff_generation:
            return
        self._show_note(message)

    # ── the plan ─────────────────────────────────────────────────────

    def _build_plan(self):
        """[(message, [paths], group)] for the groups with something ticked."""
        plan = []
        for item, key in self._iter_group_items():
            card = self.cards.get(key)
            if card is None:
                continue
            paths = self._selected_paths(item)
            if paths:
                plan.append((card.group.message.strip(), paths, card.group))
        return plan

    def _update_actions(self):
        busy = self._commit_worker is not None
        state = self.state
        blocked = state.blocked if state else "Reading…"
        plan = self._build_plan() if state else []

        total_files = sum(len(paths) for _m, paths, _g in plan)
        unready = [group for _m, _p, group in plan if not group.ready()]

        # Deliberately NOT gated on `unready`: a click on a group that still
        # needs a description is answered by jumping to that box, which is
        # more use than a button that cannot be pressed at all. See the
        # module docstring.
        can_act = bool(plan) and not blocked and not busy
        self.commit_button.setEnabled(can_act)
        self.commit_push_button.setEnabled(can_act)
        self.push_only_button.setEnabled(
            not busy and state is not None and not state.detached
            and not state.unborn and (state.ahead > 0 or not state.upstream))
        self.refresh_button.setEnabled(not busy)
        self.check_all.setEnabled(not busy and bool(self.groups))
        self.check_none.setEnabled(not busy and bool(self.groups))
        for button in (self.empty_page.refresh_button,
                       self.empty_page.push_button,
                       self.empty_page.ignored_button):
            button.setEnabled(not busy)

        if busy:
            return
        if blocked:
            self.status_label.setText(blocked)
        elif not self.groups:
            self.status_label.setText(
                f"Working tree is clean · {state.branch}" if state else "")
        elif not plan:
            self.status_label.setText("Nothing ticked.")
        elif unready:
            names = ", ".join(group.label for group in unready)
            self.status_label.setText(
                f"{len(unready)} group(s) still need a message: {names}. "
                f"Type one, or press Commit to jump to it.")
        else:
            self.status_label.setText(
                f"{len(plan)} commit(s) · {total_files} file(s) · all ready.")

    # ── committing ───────────────────────────────────────────────────

    def _start_commit(self, push: bool):
        plan = self._build_plan()
        if not plan:
            return
        unready = [group for _m, _p, group in plan if not group.ready()]
        if unready:
            self._demand_description(unready)
            return
        if not self._confirm(plan, push):
            return
        expected = {change.path: change.status for change in self.state.changes}
        self._start_worker(
            [(message, paths) for message, paths, _g in plan],
            push, expected, "Committing…")

    def _start_worker(self, plan, push, expected, message):
        self.log.clear()
        self._set_log_visible(True)
        self._set_busy(True, message)
        self.progress.setRange(0, len(plan) + (1 if push else 0))
        self.progress.setValue(0)
        self.progress.show()

        worker = CommitWorker(self.repo, plan, push, expected, self)
        worker.log.connect(self._append_log)
        worker.progress.connect(lambda done, _total: self.progress.setValue(done))
        worker.done.connect(self._on_commit_done)
        self._commit_worker = worker
        self._update_actions()
        worker.start()

    def _demand_description(self, unready):
        """Answer a refused click by showing exactly what is missing.

        Nothing is committed, the offending cards are outlined, and the caret
        lands in the first one. The log gets the reason in full, because the
        status bar is one line and this is the question people hit most.
        """
        for group in unready:
            card = self.cards.get(group.key)
            if card is not None:
                card.set_alert(True)
        first = self.cards.get(unready[0].key)
        if first is not None:
            self.cards_area.ensureWidgetVisible(first)
            first.demand_input()
        names = ", ".join(group.label for group in unready)
        self.status_label.setText(
            f"Nothing committed — {len(unready)} group(s) still need a "
            f"description: {names}. Type one in the highlighted box.")
        self._append_log(
            f"Refused: {names} still carries only its prefix. "
            f"post: and update: are filled in automatically from the post "
            f"titles; config:, fix: and remove: describe intent, so they are "
            f"yours to write.")

    def _confirm(self, plan, push: bool) -> bool:
        lines = []
        for index, (message, paths, _group) in enumerate(plan):
            lines.append(f"{badge_for(index)} {message}   "
                         f"({files_label(len(paths))})")

        warning = ""
        removing = sum(len(p) for _m, p, g in plan if g.kind == "remove")
        if removing:
            warning += (f"\n⚠ Includes {removing} deletion(s); getting them "
                        f"back afterwards needs git.")
        if push and self.state.behind:
            warning += (f"\n⚠ The remote is {self.state.behind} commit(s) "
                        f"ahead of you, so the push will most likely be "
                        f"rejected. Consider `git pull --rebase` first.")
        if push:
            warning += ("\n\nPushing starts the GitHub Actions build and "
                        "deploys the site.")

        box = QMessageBox(self)
        box.setIcon(QMessageBox.Icon.Question)
        box.setWindowTitle("Confirm commit" + (" and push" if push else ""))
        box.setText(f"Create {len(plan)} commit(s)"
                    + (", then push to origin:" if push else ":"))
        box.setInformativeText("\n".join(lines) + warning)
        box.setStandardButtons(QMessageBox.StandardButton.Ok
                               | QMessageBox.StandardButton.Cancel)
        box.setDefaultButton(QMessageBox.StandardButton.Cancel)
        return box.exec() == QMessageBox.StandardButton.Ok

    def _on_push_only(self):
        if self.state is None:
            return
        note = ""
        if self.state.behind:
            note = (f"\n⚠ The remote is {self.state.behind} commit(s) ahead of "
                    f"you, so the push will most likely be rejected.")
        answer = QMessageBox.question(
            self, "Confirm push",
            f"Push {self.state.branch} to origin — "
            f"{self.state.ahead} local commit(s) ahead."
            f"{note}\n\nPushing starts the GitHub Actions deploy.",
            QMessageBox.StandardButton.Ok | QMessageBox.StandardButton.Cancel,
            QMessageBox.StandardButton.Cancel)
        if answer != QMessageBox.StandardButton.Ok:
            return
        self._start_worker([], True, {}, "Pushing…")

    def _on_commit_done(self, ok: bool, summary: str):
        self._commit_worker = None
        self.progress.hide()
        self._append_log(("✔ " if ok else "✘ ") + summary.replace("\n", " "))
        self.preserved.clear()
        self._set_busy(False)
        if ok:
            self.status_label.setText(summary)
        else:
            QMessageBox.warning(self, "Did not finish", summary)
        self.refresh()

    # ── odds and ends ────────────────────────────────────────────────

    def _set_log_visible(self, visible: bool):
        self.log.setVisible(visible)
        self.log_toggle.setText("▾ Log" if visible else "▸ Log")
        if self.log_toggle.isChecked() != visible:
            blocked = self.log_toggle.blockSignals(True)
            self.log_toggle.setChecked(visible)
            self.log_toggle.blockSignals(blocked)

    def _append_log(self, line: str):
        self.log.appendPlainText(line)
        if not self.log.isVisible():
            self._set_log_visible(True)
        bar = self.log.verticalScrollBar()
        bar.setValue(bar.maximum())

    def _set_busy(self, busy: bool, message: str = ""):
        if busy and message:
            self.status_label.setText(message)
        self.setCursor(Qt.CursorShape.BusyCursor if busy
                       else Qt.CursorShape.ArrowCursor)
        if not busy:
            self._update_actions()

    def resizeEvent(self, event):
        super().resizeEvent(event)
        self._fit_cards_pane()

    def closeEvent(self, event):
        if self._commit_worker is not None and self._commit_worker.isRunning():
            answer = QMessageBox.question(
                self, "Still working",
                "A commit or push is still running. Close anyway?\n"
                "Commits already made are kept; the one in flight is cut off.",
                QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No,
                QMessageBox.StandardButton.No)
            if answer != QMessageBox.StandardButton.Yes:
                event.ignore()
                return
            self._commit_worker.cancel()
            self._commit_worker.wait(5000)

        unsaved = [card for card in self.cards.values()
                   if card.group.user_edited and card.group.message.strip()]
        if unsaved and self._commit_worker is None:
            answer = QMessageBox.question(
                self, "Unsaved messages",
                f"{len(unsaved)} hand-written commit message(s) have not been "
                f"committed and will be lost.\nClose anyway?",
                QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No,
                QMessageBox.StandardButton.No)
            if answer != QMessageBox.StandardButton.Yes:
                event.ignore()
                return

        for worker in list(self._workers):
            worker.requestInterruption()
            worker.wait(2000)
        event.accept()
