# Generated by Claude
"""Background threads. Nothing here touches a widget.

Every git call the window makes runs on one of these. A `status` over 800
posts takes tens of milliseconds and would be fine inline, but a push is
network-bound and a fetch behind a credential prompt can sit for a minute --
and a frozen window during a push is exactly when the user most wants to see
what is happening.

The commit thread is the careful one. Its contract:

* **Re-read before writing.** The plan on screen was computed from a scan
  that may be seconds old. If any selected path has changed status since,
  the whole run is abandoned before the first commit, not halfway through.
* **Pathspecs through a file.** `--pathspec-from-file --pathspec-file-nul`
  instead of arguments: a group can hold a post plus twenty numbered images,
  and Windows caps a command line at ~32k characters. It also sidesteps
  every quoting question about spaces and non-ASCII in the paths.
* **Commit by pathspec.** `git commit -- <paths>` records the worktree state
  of exactly those paths and leaves anything else staged in the index alone,
  so a group never picks up a neighbour's file.
* **Stop at the first failure.** Commits already made are reported and kept
  (they are real history); nothing further is attempted.
"""
from __future__ import annotations

import os
import tempfile
import threading

from PySide6.QtCore import QThread, Signal

from . import gitcmd, model, rules

# git prints one of these when a pathspec commit finds nothing to record --
# a file that was touched but whose content is identical to HEAD.
_NOTHING_TO_COMMIT = ("nothing to commit", "no changes added to commit",
                      "nothing added to commit")


class ScanWorker(QThread):
    """Read the working tree and build the commit plan.

    Carries the scan generation it was started for. A refresh clears and
    rebuilds the tree, so a result from a superseded scan must be dropped
    rather than applied to widgets that no longer exist.
    """

    scanned = Signal(int, object, object, object)   # gen, state, groups, texts
    failed = Signal(int, str)

    def __init__(self, repo, generation, parent=None):
        super().__init__(parent)
        self.repo = repo
        self.generation = generation

    def run(self):
        try:
            state = model.scan(self.repo)
            contents = rules.titles_map(self.repo, state.changes)
            groups = rules.build_groups(self.repo, state.changes)
            self.scanned.emit(self.generation, state, groups, contents)
        except Exception as exc:
            self.failed.emit(self.generation, str(exc))


class IgnoredWorker(QThread):
    """List what .gitignore is hiding, so the user can confirm it on purpose."""

    listed = Signal(int, object, int)
    failed = Signal(int, str)

    def __init__(self, repo, generation, parent=None):
        super().__init__(parent)
        self.repo = repo
        self.generation = generation

    def run(self):
        try:
            paths, total = model.scan_ignored(self.repo)
            self.listed.emit(self.generation, paths, total)
        except Exception as exc:
            self.failed.emit(self.generation, str(exc))


class DiffWorker(QThread):
    """Produce the preview for one file.

    `kind` tells the window which page of the preview stack to show:
    "text" (a unified diff), "image" (an absolute path to load), "note"
    (binary, too large, or nothing to show).
    """

    ready = Signal(int, str, str, str)     # generation, path, kind, payload
    failed = Signal(int, str)

    def __init__(self, repo, change, generation, parent=None):
        super().__init__(parent)
        self.repo = repo
        self.change = change
        self.generation = generation

    def run(self):
        change = self.change
        try:
            if change.is_image and change.status != "D":
                full = os.path.join(self.repo,
                                    change.path.replace("/", os.sep))
                if os.path.exists(full):
                    self.ready.emit(self.generation, change.path, "image", full)
                    return

            if change.untracked:
                self.ready.emit(self.generation, change.path,
                                *self._new_file(change))
                return

            result = gitcmd.run(
                self.repo,
                ["diff", "HEAD", "--no-renames", "--", gitcmd.literal(change.path)],
                check=False)
            text = result.text
            if result.code != 0 and not text:
                note = result.err.strip() or "Could not read this file's diff."
                self.ready.emit(self.generation, change.path, "note", note)
                return
            if not text.strip():
                self.ready.emit(self.generation, change.path, "note",
                                "No content change (file mode or line endings only).")
                return
            self.ready.emit(self.generation, change.path, "text",
                            _clip(text))
        except Exception as exc:
            self.failed.emit(self.generation, str(exc))

    def _new_file(self, change):
        """Render an untracked file as an all-added diff.

        `git diff HEAD` cannot see a file git does not know about, so the
        preview is built by hand rather than left blank -- "new file, no
        preview" is the one case where the user most wants to look.
        """
        full = os.path.join(self.repo, change.path.replace("/", os.sep))
        try:
            size = os.path.getsize(full)
        except OSError as exc:
            return "note", f"Could not read: {exc}"
        if size > model.MAX_PREVIEW_BYTES:
            return "note", (f"New file, {_human(size)} — larger than the "
                            f"preview limit, contents not shown.")
        try:
            with open(full, "rb") as handle:
                data = handle.read()
        except OSError as exc:
            return "note", f"Could not read: {exc}"
        if b"\0" in data[:model.BINARY_SNIFF_BYTES]:
            return "note", f"New binary file, {_human(size)}."
        body = data.decode("utf-8", "replace")
        lines = body.splitlines()
        head = [f"New file {change.display}",
                f"@@ {len(lines)} lines @@"]
        shown = lines[:model.MAX_PREVIEW_LINES]
        rendered = head + ["+" + line for line in shown]
        if len(lines) > len(shown):
            rendered.append(f"... {len(lines) - len(shown)} more lines not shown")
        return "text", "\n".join(rendered)


class CommitWorker(QThread):
    """Commit each group in turn, then optionally push. See module docstring."""

    log = Signal(str)
    progress = Signal(int, int)             # done, total
    done = Signal(bool, str)                # ok, summary

    def __init__(self, repo, plan, push, expected, parent=None):
        super().__init__(parent)
        self.repo = repo
        self.plan = plan                    # [(message, [paths])]
        self.push = push
        self.expected = expected            # {path: effective status}
        self.cancelled = threading.Event()
        self._temp_files: list[str] = []

    def cancel(self):
        self.cancelled.set()

    # ---- helpers ----

    def _temp(self, data: bytes, suffix: str) -> str:
        handle = tempfile.NamedTemporaryFile(
            delete=False, suffix=suffix, prefix="commitgui-")
        try:
            handle.write(data)
        finally:
            handle.close()
        self._temp_files.append(handle.name)
        return handle.name

    def _pathspec_file(self, paths) -> str:
        blob = b"\0".join(
            gitcmd.literal(p).encode("utf-8", "surrogateescape") for p in paths)
        return self._temp(blob, ".pathspec")

    def _cleanup(self):
        for name in self._temp_files:
            try:
                os.unlink(name)
            except OSError:
                pass
        self._temp_files.clear()

    def _preflight(self) -> str:
        """Re-scan and confirm the plan still describes the working tree."""
        state = model.scan(self.repo)
        # `blocked` answers "may I commit". Push-only runs carry an empty
        # plan and must not be refused because the working tree happens to
        # hold a conflict -- pushing history that is already committed is
        # unaffected by the state of the tree.
        if self.plan and state.blocked:
            return state.blocked
        current = {c.path: c.status for c in state.changes}
        for _message, paths in self.plan:
            for path in paths:
                if path not in current:
                    return (f"The working tree changed after the last scan, "
                            f"so nothing was committed:\n"
                            f"{gitcmd.for_display(path)} is no longer a "
                            f"pending change.")
                if current[path] != self.expected.get(path):
                    return (f"The working tree changed after the last scan, "
                            f"so nothing was committed:\n"
                            f"{gitcmd.for_display(path)} went from "
                            f"{self.expected.get(path)} to {current[path]}.")
        return ""

    # ---- the run ----

    def run(self):
        made = 0
        try:
            self.log.emit("Checking the working tree…")
            problem = self._preflight()
            if problem:
                self.done.emit(False, problem)
                return

            total = len(self.plan) + (1 if self.push else 0)
            for index, (message, paths) in enumerate(self.plan, start=1):
                if self.cancelled.is_set():
                    self.done.emit(False, f"Cancelled. {made} commit(s) were made.")
                    return
                ok, note = self._commit_one(message, paths)
                self.progress.emit(index, total)
                if not ok:
                    self.done.emit(
                        False, f"{note}\n\n{made} commit(s) were made; "
                               f"the rest were not attempted.")
                    return
                if note == "skipped":
                    self.log.emit(f"  skipped — no actual content change: {message}")
                else:
                    made += 1
                    self.log.emit(f"  ✔ {message}")

            if not self.push:
                self.done.emit(True, f"Done — {made} commit(s). Not pushed.")
                return

            if made == 0:
                self.log.emit("No new commits; pushing what is already local.")
            ok, summary = self._push()
            self.progress.emit(len(self.plan) + 1, len(self.plan) + 1)
            self.done.emit(ok, f"{made} commit(s). {summary}")
        except gitcmd.GitFailed as exc:
            self.done.emit(False, f"git failed: {exc}")
        except Exception as exc:
            self.done.emit(False, f"Unexpected error: {exc}")
        finally:
            self._cleanup()

    def _commit_one(self, message: str, paths):
        self.log.emit(f"Committing {len(paths)} file(s): {message}")
        spec = self._pathspec_file(paths)

        staged = gitcmd.run(
            self.repo, ["add", "-A", f"--pathspec-from-file={spec}",
                        "--pathspec-file-nul"], check=False)
        if staged.code != 0:
            return False, f"git add failed: {staged.err.strip()}"

        body = message.strip() + "\n"
        msg_file = self._temp(body.encode("utf-8"), ".msg")
        committed = gitcmd.run(
            self.repo, ["commit", "-F", msg_file, "--cleanup=whitespace",
                        f"--pathspec-from-file={spec}", "--pathspec-file-nul"],
            check=False)
        if committed.code != 0:
            blob = (committed.text + committed.err).lower()
            if any(phrase in blob for phrase in _NOTHING_TO_COMMIT):
                return True, "skipped"
            detail = (committed.err.strip() or committed.text.strip()
                      or f"exit {committed.code}")
            return False, f"git commit failed: {detail}"
        return True, ""

    def _push(self):
        """Push the current branch, streaming git's own output to the log."""
        state = model.scan(self.repo)
        if state.detached:
            return False, "HEAD is detached — nothing was pushed."
        branch = state.branch
        args = ["push", "--porcelain", "--progress"]
        if not state.upstream:
            args.append("--set-upstream")
            self.log.emit(f"{branch} has no upstream; setting origin/{branch}.")
        args += ["origin", f"refs/heads/{branch}:refs/heads/{branch}"]

        self.log.emit(f"Pushing {branch} → origin …")
        seen: list[str] = []

        def on_line(line):
            seen.append(line)
            self.log.emit("  " + line)

        code = gitcmd.stream(self.repo, args, on_line,
                             cancelled=self.cancelled)
        # (ok, summary) -- the same shape as the early return above. Returning
        # the bare string here made `ok, summary = self._push()` unpack a
        # sentence into two names.
        return code == 0, self._explain_push(code, seen)

    @staticmethod
    def _explain_push(code, lines):
        """One sentence of plain language on top of git's raw output."""
        joined = "\n".join(lines)
        lowered = joined.lower()
        if code == 0:
            if any(line.startswith("=") for line in lines):
                return "The remote was already up to date; nothing to push."
            return ("Push succeeded. GitHub Actions has started; the site is "
                    "usually live in a minute or two.")
        if "non-fast-forward" in lowered or "fetch first" in lowered or \
                "rejected" in lowered:
            return ("Push rejected: the remote has commits you do not. Run "
                    "`git pull --rebase` on the command line, then retry.")
        if ("could not read" in lowered or "authentication" in lowered
                or "terminal prompts disabled" in lowered
                or "returned error: 403" in lowered):
            return ("Push failed on credentials. Run `git push` once on the "
                    "command line to authenticate, then come back here.")
        if "could not resolve host" in lowered or "unable to access" in lowered:
            return "Push failed: could not reach GitHub. Check the network."
        if code == -1:
            return "Push was cancelled or timed out."
        return f"Push failed (exit {code}); see the log above."


def _clip(text: str) -> str:
    lines = text.splitlines()
    if len(lines) <= model.MAX_PREVIEW_LINES:
        return text
    kept = lines[:model.MAX_PREVIEW_LINES]
    kept.append(f"... {len(lines) - len(kept)} more lines not shown")
    return "\n".join(kept)


def _human(size: int) -> str:
    for unit in ("B", "KB", "MB", "GB"):
        if size < 1024 or unit == "GB":
            return f"{size:.0f} {unit}" if unit == "B" else f"{size:.1f} {unit}"
        size /= 1024.0
    return f"{size:.1f} GB"
