# Generated by Claude
"""Launcher for the commit window.

    python tools\\commit_gui.py [repo path]

A plain script rather than `python -m commitgui`, because that only works
when `tools/` happens to be on sys.path. This puts it there and then hands
over to the package.

The import is guarded: launched from `commit-gui.cmd` there is no console, so
a missing PySide6 would otherwise be a program that starts and vanishes. A
native message box is the only thing available before Qt exists.
"""
from __future__ import annotations

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))


def _fatal(text: str) -> int:
    sys.stderr.write(text + "\n")
    if sys.platform == "win32":
        try:
            import ctypes
            ctypes.windll.user32.MessageBoxW(None, text, "Commit GUI", 0x10)
        except Exception:
            pass
    return 2


def main() -> int:
    try:
        from commitgui.main import main as run
    except ImportError as exc:
        return _fatal(
            "Could not start: a dependency is missing.\n\n"
            f"{exc}\n\n"
            "Install PySide6 with:\n"
            "    pip install PySide6")
    return run(sys.argv)


if __name__ == "__main__":
    raise SystemExit(main())
