@echo off
rem Generated by Claude -- launcher for the commit review window.
rem Uses pythonw so the GUI does not drag a console window along; falls back
rem to python when pythonw is missing, so any startup error stays readable.
setlocal
set "HERE=%~dp0"
where pythonw >/dev/null 2>nul
if errorlevel 1 goto useconsole
start "Commit GUI" pythonw "%HERE%commit_gui.py" %*
goto done
:useconsole
python "%HERE%commit_gui.py" %*
:done
endlocal
