# Generated by Claude
"""Self-test for the commit window's non-GUI half.

Follows the convention of the sibling tools (ValueCheck's `selftest_*.py`):
one script, no framework, run it and read the last line.

    python tools\\selftest_commitgui.py

It builds a throwaway repository in the temp directory and exercises the
things that are easy to get wrong and invisible until they bite:

* CJK and spaces in filenames, end to end -- porcelain parsing, grouping,
  pathspec files, and the commit that comes out the other side.
* Front matter titles in every shape the repo actually contains.
* Grouping, including the "no file is ever dropped" property, which is
  checked by counting rather than by inspection.
* Regenerating a message after a file is unticked.

Nothing here touches the blog repository.
"""
from __future__ import annotations

import os
import shutil
import subprocess
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from commitgui import gitcmd, model, rules
from commitgui.workers import CommitWorker

FAILURES: list[str] = []
CHECKS = 0


def check(condition, label, detail=""):
    global CHECKS
    CHECKS += 1
    if not condition:
        FAILURES.append(f"{label}{(': ' + detail) if detail else ''}")
        print(f"  FAIL  {label}{(': ' + detail) if detail else ''}")
    else:
        print(f"  ok    {label}")


def equal(got, want, label):
    check(got == want, label, f"got {got!r}, want {want!r}")


# ── pure functions ────────────────────────────────────────────────────────

def test_effective_status():
    print("\n[status codes]")
    cases = {
        ("?", "?"): "A", ("A", " "): "A", ("A", "M"): "A",
        ("M", " "): "M", (" ", "M"): "M", ("M", "M"): "M",
        ("D", " "): "D", (" ", "D"): "D",
        ("U", "U"): "U", ("A", "A"): "U", ("D", "U"): "U",
        ("!", "!"): "!",
    }
    for (x, y), want in cases.items():
        equal(model._effective_status(x, y), want, f"{x}{y} -> {want}")


def test_porcelain_parse():
    print("\n[porcelain parsing]")
    raw = (b"?? _posts/2026-9-5-\xe6\x96\xb0\xe4\xb9\xa6 \xe5\x90\x8d.md\0"
           b" M _config.yml\0"
           b"A  images/a b.png\0"
           b"!! _site/\0")
    got = list(model._parse_porcelain(raw))
    equal(len(got), 4, "four records")
    equal(got[0][2], "_posts/2026-9-5-新书 名.md", "CJK + space path")
    equal(got[1], (" ", "M", "_config.yml"), "unstaged: X blank, Y=M")
    equal(got[2], ("A", " ", "images/a b.png"), "staged add: X=A, Y blank")
    equal(got[3][0], "!", "ignored marker")
    # A record shorter than "XY p" must be skipped, not crash.
    equal(list(model._parse_porcelain(b"\0??\0")), [], "short records skipped")


def test_front_matter():
    print("\n[front matter titles]")
    samples = [
        ("---\nlayout: post\ntitle:  What I Learned\ncategories: [x]\n---\nbody",
         "What I Learned", "two spaces after colon (repo's own style)"),
        ('---\ntitle: "Quoted Title"\n---\n', "Quoted Title", "double quotes"),
        ("---\ntitle: '单引号标题'\n---\n", "单引号标题", "single quotes, CJK"),
        ("﻿---\ntitle: With BOM\n---\n", "With BOM", "leading BOM"),
        ("no front matter here", "", "no front matter"),
        ("---\nlayout: post\n---\n", "", "front matter without title"),
        ("---\ntitle: Trailing   \n---\n", "Trailing", "trailing whitespace"),
    ]
    for text, want, label in samples:
        equal(rules._front_matter_title(text), want, label)


def test_normalise():
    print("\n[image name matching]")
    equal(rules._normalise("Where_the_Money_Is_3.png"), "where the money is",
          "numbered cover")
    equal(rules._normalise("Where_the_Money_Is.png"), "where the money is",
          "unnumbered cover")
    equal(rules._normalise("What I Learned About Investing from Darwin.png"),
          "what i learned about investing from darwin", "spaces already")


def test_is_ready():
    print("\n[message readiness]")
    equal(rules.is_ready("post: A Book"), True, "filled")
    equal(rules.is_ready("fix: "), False, "bare prefix with space")
    equal(rules.is_ready("fix:"), False, "bare prefix")
    equal(rules.is_ready("   "), False, "whitespace only")
    equal(rules.is_ready(""), False, "empty")
    equal(rules.is_ready("config: 改了 url"), True, "CJK description")


# ── a real repository ─────────────────────────────────────────────────────

def git(repo, *args, check_ok=True):
    result = subprocess.run(
        ["git", "-c", "core.quotepath=false", *args], cwd=repo,
        capture_output=True)
    if check_ok and result.returncode != 0:
        raise RuntimeError(f"git {' '.join(args)}: "
                           f"{result.stderr.decode('utf-8', 'replace')}")
    return result.stdout.decode("utf-8", "replace")


def write(repo, path, text):
    full = os.path.join(repo, path.replace("/", os.sep))
    os.makedirs(os.path.dirname(full), exist_ok=True)
    with open(full, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)


def write_png(repo, path):
    full = os.path.join(repo, path.replace("/", os.sep))
    os.makedirs(os.path.dirname(full), exist_ok=True)
    with open(full, "wb") as handle:                 # PNG magic carries NULs,
        handle.write(b"\x89PNG\r\n\x1a\n" + b"\0" * 64)   # so it sniffs binary


def post(title, body="内容"):
    return (f"---\nlayout: post\ntitle:  {title}\n"
            f"categories: [Books]\ntags: [x]\n---\n{body}\n")


def build_repo(root):
    git(root, "init", "-b", "master", "-q")
    git(root, "config", "user.email", "test@example.com")
    git(root, "config", "user.name", "Selftest")
    git(root, "config", "core.autocrlf", "false")

    write(root, "_config.yml", "title: blog\nurl: \"\"\n")
    write(root, ".gitignore", "_site/\n__pycache__/\n")
    write(root, "_posts/Investing/2025-5-16-business quotes.md",
         post("business quotes"))
    write(root, "_posts/2026-1-1-Old Book.md", post("Old Book"))
    write(root, "_posts/2020-2-2-优秀的绵羊.md", post("优秀的绵羊"))
    git(root, "add", "-A")
    git(root, "commit", "-qm", "first commit")


def mutate(root):
    """One of every kind of change this tool has to name."""
    # a new post plus its cover, referenced from the body -- CJK and a space
    write(root, "_posts/2026-9-5-新的书 名.md",
          post("新的书 名", "![封面](/images/新的书 名.png)\n正文"))
    write_png(root, "images/新的书 名.png")
    # a second new post, older date, to check ordering in the subject
    write(root, "_posts/2026-8-2-Another Book.md", post("Another Book"))
    # a modified post
    write(root, "_posts/Investing/2025-5-16-business quotes.md",
          post("business quotes", "新增一句引言"))
    # a modified CJK post
    write(root, "_posts/2020-2-2-优秀的绵羊.md", post("优秀的绵羊", "改动"))
    # configuration
    write(root, "_config.yml", "title: blog\nurl: \"https://example.com\"\n")
    # a script - the case the user asked about explicitly
    write(root, "tools/helper.py", "print('hi')\n")
    # something ignored, which must never show up as committable
    write(root, "_site/index.html", "<html></html>")
    # a deletion
    os.unlink(os.path.join(root, "_posts", "2026-1-1-Old Book.md"))


def test_repo():
    print("\n[live repository]")
    root = tempfile.mkdtemp(prefix="commitgui-selftest-")
    try:
        build_repo(root)
        mutate(root)

        state = model.scan(root)
        paths = {c.path: c for c in state.changes}

        equal(state.branch, "master", "branch name")
        equal(state.blocked, "", "nothing blocking a commit")
        check("_site/index.html" not in paths, "ignored file is not listed")
        check("tools/helper.py" in paths, "untracked .py IS listed",
              f"saw {sorted(paths)}")
        equal(paths["tools/helper.py"].status, "A", "untracked -> A")
        equal(paths["_posts/2026-1-1-Old Book.md"].status, "D", "deletion -> D")
        equal(paths["_config.yml"].status, "M", "config -> M")
        check(paths["images/新的书 名.png"].binary, "PNG detected as binary")
        check(paths["_posts/2026-9-5-新的书 名.md"].added > 0,
              "untracked text file has a line count",
              str(paths["_posts/2026-9-5-新的书 名.md"].added))
        check(paths["_posts/Investing/2025-5-16-business quotes.md"].added > 0,
              "modified file has numstat counts")

        ignored, total = model.scan_ignored(root)
        check(any("_site" in p for p in ignored), "_site appears under ignored",
              str(ignored))
        check(total < 50, "ignored listing stays collapsed", str(total))

        # ---- grouping ----
        groups = rules.build_groups(root, state.changes)
        by_kind = {g.kind: g for g in groups}
        equal(sorted(by_kind), ["config", "other", "post", "remove", "update"],
              "all five kinds present")

        grouped = [c.path for g in groups for c in g.changes]
        equal(len(grouped), len(state.changes), "no change is dropped")
        equal(len(set(grouped)), len(grouped), "no change is duplicated")
        equal(set(grouped), set(paths), "grouped set == scanned set")

        post_paths = {c.path for c in by_kind["post"].changes}
        check("images/新的书 名.png" in post_paths,
              "cover follows its post into the post group", str(post_paths))
        check("tools/helper.py" in {c.path for c in by_kind["other"].changes},
              "the .py lands in the group that asks for a description")

        equal(by_kind["post"].message, "post: Another Book, 新的书 名",
              "post subject, titles in post-date order")
        equal(by_kind["update"].message, "update: 优秀的绵羊, business quotes",
              "update subject (2020 post before 2025 post)")
        equal(by_kind["config"].message, "config: ", "config left for the user")
        equal(by_kind["other"].message, "fix: ", "other left for the user")
        equal(by_kind["remove"].message, "remove: ", "remove left for the user")

        equal(by_kind["post"].ready(), True, "auto group is ready")
        equal(by_kind["config"].ready(), False, "manual group is not ready")

        # ---- unticking rewrites the generated subject ----
        contents = rules.titles_map(root, state.changes)
        kept = [c.path for c in by_kind["post"].changes
                if "Another" not in c.path]
        equal(rules.message_for(by_kind["post"], contents, kept),
              "post: 新的书 名", "subject follows the ticked files")

        # ---- the commit itself ----
        expected = {c.path: c.status for c in state.changes}
        plan = [
            (by_kind["post"].message,
             [c.path for c in by_kind["post"].changes]),
            (by_kind["update"].message,
             [c.path for c in by_kind["update"].changes]),
            ("config: point url at example.com", ["_config.yml"]),
        ]
        worker = CommitWorker(root, plan, push=False, expected=expected)
        results = {}
        worker.done.connect(lambda ok, text: results.update(ok=ok, text=text))
        worker.log.connect(lambda line: None)
        worker.run()                     # synchronous: no event loop needed

        check(results.get("ok") is True, "commit run reported success",
              str(results.get("text")))

        subjects = git(root, "log", "--pretty=%s", "-3").splitlines()
        equal(subjects[0], "config: point url at example.com", "3rd subject")
        equal(subjects[1], "update: 优秀的绵羊, business quotes", "2nd subject")
        equal(subjects[2], "post: Another Book, 新的书 名", "1st subject")

        files = git(root, "show", "--name-only", "--pretty=", "HEAD~2")
        listed = set(files.split("\n")) - {""}
        equal(listed, {"_posts/2026-8-2-Another Book.md",
                       "_posts/2026-9-5-新的书 名.md",
                       "images/新的书 名.png"},
              "post commit holds exactly its group, CJK intact")

        # The three groups left out must still be pending, untouched.
        after = {c.path: c.status for c in model.scan(root).changes}
        equal(set(after), {"_posts/2026-1-1-Old Book.md", "tools/helper.py"},
              "unselected groups are left alone")

        # ---- guards ----
        stale = CommitWorker(root, [("x: y", ["tools/helper.py"])], False,
                             {"tools/helper.py": "M"})     # wrong status
        stale_result = {}
        stale.done.connect(lambda ok, text: stale_result.update(ok=ok, text=text))
        stale.log.connect(lambda line: None)
        stale.run()
        equal(stale_result.get("ok"), False, "stale plan is refused")
        check("changed after the last scan" in stale_result.get("text", ""),
              "refusal explains why", stale_result.get("text", ""))

        # A merge left in progress must block everything.
        with open(os.path.join(root, ".git", "MERGE_HEAD"), "w") as handle:
            handle.write("0" * 40 + "\n")
        blocked = model.scan(root)
        check("merge is in progress" in blocked.blocked,
              "merge in progress blocks committing", blocked.blocked)
        os.unlink(os.path.join(root, ".git", "MERGE_HEAD"))

    finally:
        shutil.rmtree(root, ignore_errors=True)


def test_push():
    """Push against a bare repository in the temp directory.

    No network involved. This is the path that shipped broken once: `_push`
    returned a string where the caller unpacked a pair, and every check here
    would have caught it, because all of them go through that return value.
    """
    print("\n[push, against a local bare remote]")
    root = tempfile.mkdtemp(prefix="commitgui-push-")
    remote = tempfile.mkdtemp(prefix="commitgui-remote-")
    clone = tempfile.mkdtemp(prefix="commitgui-clone-")
    try:
        git(remote, "init", "--bare", "-q", "--initial-branch=master")
        build_repo(root)
        git(root, "remote", "add", "origin", remote)

        # ---- first push: also sets the upstream ----
        write(root, "_posts/2026-9-9-Pushed Book.md", post("Pushed Book"))
        state = model.scan(root)
        equal(state.upstream, "", "no upstream before the first push")
        worker = CommitWorker(
            root, [("post: Pushed Book", ["_posts/2026-9-9-Pushed Book.md"])],
            push=True, expected={c.path: c.status for c in state.changes})
        got = {}
        worker.done.connect(lambda ok, text: got.update(ok=ok, text=text))
        worker.log.connect(lambda line: None)
        worker.run()

        check(got.get("ok") is True, "push reported success",
              str(got.get("text")))
        check("Push succeeded" in got.get("text", ""),
              "success is explained in words", got.get("text", ""))
        equal(git(remote, "log", "--pretty=%s", "-1").strip(),
              "post: Pushed Book", "the bare remote received the commit")

        after = model.scan(root)
        equal(after.upstream, "origin/master", "--set-upstream took effect")
        equal((after.ahead, after.behind), (0, 0), "in sync after pushing")

        # ---- second push with nothing new ----
        idle = CommitWorker(root, [], push=True, expected={})
        got2 = {}
        idle.done.connect(lambda ok, text: got2.update(ok=ok, text=text))
        idle.log.connect(lambda line: None)
        idle.run()
        check(got2.get("ok") is True, "a no-op push is not a failure",
              str(got2.get("text")))
        check("up to date" in got2.get("text", ""),
              "no-op push says the remote is up to date",
              got2.get("text", ""))

        # ---- a genuine non-fast-forward rejection ----
        subprocess.run(["git", "clone", "-q", remote, clone],
                       capture_output=True, check=True)
        git(clone, "config", "user.email", "other@example.com")
        git(clone, "config", "user.name", "Someone Else")
        write(clone, "_posts/2026-9-10-Their Book.md", post("Their Book"))
        git(clone, "add", "-A")
        git(clone, "commit", "-qm", "post: Their Book")
        git(clone, "push", "-q", "origin", "master")

        write(root, "_posts/2026-9-11-My Book.md", post("My Book"))
        state3 = model.scan(root)
        rejected = CommitWorker(
            root, [("post: My Book", ["_posts/2026-9-11-My Book.md"])],
            push=True, expected={c.path: c.status for c in state3.changes})
        got3 = {}
        rejected.done.connect(lambda ok, text: got3.update(ok=ok, text=text))
        rejected.log.connect(lambda line: None)
        rejected.run()
        equal(got3.get("ok"), False, "non-fast-forward push fails")
        check("rejected" in got3.get("text", "").lower(),
              "rejection is named as such", got3.get("text", ""))
        check("pull --rebase" in got3.get("text", ""),
              "rejection says what to do next", got3.get("text", ""))
        equal(git(root, "log", "--pretty=%s", "-1").strip(), "post: My Book",
              "the commit is kept even though the push failed")
    finally:
        for path in (root, remote, clone):
            shutil.rmtree(path, ignore_errors=True)


def test_edges():
    """The states that are rare here but wrong in an obvious way when hit."""
    print("\n[edge cases]")
    root = tempfile.mkdtemp(prefix="commitgui-edge-")
    remote = tempfile.mkdtemp(prefix="commitgui-edge-remote-")
    try:
        # ---- a repository with no commits at all ----
        git(root, "init", "-q", "-b", "master")
        git(root, "config", "user.email", "test@example.com")
        git(root, "config", "user.name", "Selftest")
        write(root, "_posts/2026-9-9-First Post.md", post("First Post"))

        state = model.scan(root)
        equal(state.branch, "master", "unborn branch is named, not blank")
        equal(state.unborn, True, "unborn is reported")
        equal(state.detached, False, "an unborn branch is NOT a detached HEAD")
        equal(state.blocked, "", "an empty repository does not block committing")

        groups = rules.build_groups(root, state.changes)
        equal([g.kind for g in groups], ["post"], "the first post groups as post")
        worker = CommitWorker(
            root, [(groups[0].message, [c.path for c in groups[0].changes])],
            push=False, expected={c.path: c.status for c in state.changes})
        got = {}
        worker.done.connect(lambda ok, text: got.update(ok=ok, text=text))
        worker.log.connect(lambda line: None)
        worker.run()
        check(got.get("ok") is True, "the root commit is made",
              str(got.get("text")))
        equal(git(root, "log", "--pretty=%s", "-1").strip(),
              "post: First Post", "root commit subject")
        equal(model.scan(root).unborn, False, "no longer unborn afterwards")

        # ---- a big text file is large, not binary ----
        write(root, "_posts/2026-9-9-Huge.md",
              post("Huge", "x" * (model.MAX_PREVIEW_BYTES + 10)))
        huge = {c.path: c for c in model.scan(root).changes}[
            "_posts/2026-9-9-Huge.md"]
        equal(huge.too_large, True, "an oversized file is flagged as large")
        equal(huge.binary, False, "an oversized text file is NOT called binary")
        equal(huge.churn(), "large file", "and says so in the Lines column")
        os.unlink(os.path.join(root, "_posts", "2026-9-9-Huge.md"))

        # ---- an image whose name normalises to nothing stays unattached ----
        write(root, "_posts/2026-9-10-Second Post.md", post("Second Post"))
        write_png(root, "images/_1.png")
        state2 = model.scan(root)
        groups2 = {g.kind: g for g in rules.build_groups(root, state2.changes)}
        post_paths = {c.path for c in groups2["post"].changes}
        check("images/_1.png" not in post_paths,
              "an image that normalises to an empty name is not swept into a post",
              str(post_paths))
        check("images/_1.png" in {c.path for c in groups2["other"].changes},
              "it lands in the group that asks for a description instead")
        os.unlink(os.path.join(root, "images", "_1.png"))

        # ---- push-only is not refused by a commit-only guard ----
        git(remote, "init", "--bare", "-q", "--initial-branch=master")
        git(root, "remote", "add", "origin", remote)
        with open(os.path.join(root, ".git", "MERGE_HEAD"), "w") as handle:
            handle.write("0" * 40 + "\n")
        check(model.scan(root).blocked != "", "the merge marker does block commits")

        pusher = CommitWorker(root, [], push=True, expected={})
        got2 = {}
        pusher.done.connect(lambda ok, text: got2.update(ok=ok, text=text))
        pusher.log.connect(lambda line: None)
        pusher.run()
        check(got2.get("ok") is True,
              "but push-only goes through anyway", str(got2.get("text")))
        equal(git(remote, "log", "--pretty=%s", "-1").strip(),
              "post: First Post", "the remote got the already-committed work")

        # and a real commit IS still refused while the marker is there
        blocked_run = CommitWorker(
            root, [("post: Second Post", ["_posts/2026-9-10-Second Post.md"])],
            push=False,
            expected={c.path: c.status for c in model.scan(root).changes})
        got3 = {}
        blocked_run.done.connect(lambda ok, text: got3.update(ok=ok, text=text))
        blocked_run.log.connect(lambda line: None)
        blocked_run.run()
        equal(got3.get("ok"), False, "committing mid-merge is still refused")
        os.unlink(os.path.join(root, ".git", "MERGE_HEAD"))
    finally:
        shutil.rmtree(root, ignore_errors=True)
        shutil.rmtree(remote, ignore_errors=True)


def test_helpers():
    print("\n[helpers]")
    equal(gitcmd.literal("a*b.md"), ":(literal)a*b.md", "pathspec is literal")
    equal(gitcmd.for_display("优秀的绵羊.md"), "优秀的绵羊.md", "display passthrough")
    broken = b"bad\xff.md".decode("utf-8", "surrogateescape")
    check("�" in gitcmd.for_display(broken),
          "undecodable byte becomes U+FFFD instead of reaching Qt")


def main():
    version = subprocess.run(["git", "--version"], capture_output=True)
    print(f"python {sys.version.split()[0]}  "
          f"{version.stdout.decode().strip()}")
    test_effective_status()
    test_porcelain_parse()
    test_front_matter()
    test_normalise()
    test_is_ready()
    test_helpers()
    test_repo()
    test_push()
    test_edges()

    print()
    if FAILURES:
        print(f"FAILED  {len(FAILURES)} of {CHECKS} checks")
        for line in FAILURES:
            print(f"  - {line}")
        return 1
    print(f"PASSED  {CHECKS} checks")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
